import {
  Organisation,
  User,
  Region,
  ExtendedField,
  FieldSets,
  Company,
  Contact,
  Deal,
  Task,
  Case,
  Event,
  Call,
  CallScript,
  Target,
  Folder,
  DocumentFile,
  EmailAccount,
  EmailMessage,
  EmailTemplate,
  Campaign,
  CustomForm,
  MessageThread,
  DirectMessage,
  SharedResource,
  AuditLogItem,
  SavedCustomView,
} from './types';

export const initialOrganisation: Organisation = {
  id: 'org-1',
  name: 'Apex Global Solutions',
  address: '100 Montgomery St, Suite 1800, San Francisco, CA 94104',
  industry: 'Enterprise Technology & Services',
  logoUrl: '',
  website: 'https://apexsolutions.example.com',
  defaultCurrency: 'USD',
  timeZone: 'America/Los_Angeles',
  sharingPolicy: 'all_shared',
};

export const initialUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Jenkins',
    email: 'sarah.j@apexsolutions.com',
    role: 'admin',
    regionId: 'reg-1',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    active: true,
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'America/Los_Angeles',
      welcomeText: 'Good day! Review your active deals and scheduled calls below.',
      clockMode: '12h',
      theme: 'light',
      activityDepth: 30,
      workingDayStart: '08:30',
      workingDayEnd: '17:30',
    },
    unavailableDates: ['2026-09-25'],
  },
  {
    id: 'user-2',
    name: 'David Ross',
    email: 'david.r@apexsolutions.com',
    role: 'manager',
    regionId: 'reg-1',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    active: true,
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'America/Los_Angeles',
      welcomeText: 'Ready for today? Track your sales pipeline and team targets.',
      clockMode: '12h',
      theme: 'light',
      activityDepth: 60,
      workingDayStart: '09:00',
      workingDayEnd: '18:00',
    },
    unavailableDates: [],
  },
  {
    id: 'user-3',
    name: 'Alex Rivera',
    email: 'alex.r@apexsolutions.com',
    role: 'standard',
    regionId: 'reg-2',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    active: true,
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'America/New_York',
      welcomeText: 'Focus on your priority call list and upcoming deal closings.',
      clockMode: '12h',
      theme: 'light',
      activityDepth: 30,
      workingDayStart: '09:00',
      workingDayEnd: '17:00',
    },
    unavailableDates: ['2026-09-21'],
  },
  {
    id: 'user-4',
    name: 'Elena Rostova',
    email: 'elena.r@apexsolutions.com',
    role: 'standard',
    regionId: 'reg-3',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    active: true,
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'Europe/London',
      welcomeText: 'Support desk active: check open high-priority customer cases.',
      clockMode: '24h',
      theme: 'light',
      activityDepth: 45,
      workingDayStart: '08:00',
      workingDayEnd: '16:30',
    },
    unavailableDates: [],
  },
];

export const initialRegions: Region[] = [
  {
    id: 'reg-1',
    name: 'North America West',
    code: 'NA-W',
    description: 'HQ and Pacific Time Zone clients',
    unavailableDates: ['2026-11-26', '2026-12-25'],
  },
  {
    id: 'reg-2',
    name: 'North America East',
    code: 'NA-E',
    description: 'Eastern seaboard commercial accounts',
    unavailableDates: ['2026-11-26', '2026-12-25'],
  },
  {
    id: 'reg-3',
    name: 'EMEA Hub (London)',
    code: 'EMEA',
    description: 'European and UK enterprise accounts',
    unavailableDates: ['2026-12-25', '2026-12-26'],
  },
];

export const initialExtendedFields: ExtendedField[] = [
  {
    id: 'ef-1',
    entity: 'company',
    label: 'Tax ID / VAT',
    key: 'vat_id',
    type: 'text',
    required: false,
  },
  {
    id: 'ef-2',
    entity: 'contact',
    label: 'LinkedIn Profile',
    key: 'linkedin_url',
    type: 'text',
    required: false,
  },
  {
    id: 'ef-3',
    entity: 'company',
    label: 'Account Tier',
    key: 'account_tier',
    type: 'select',
    options: ['Enterprise Plus', 'Growth Tier', 'Strategic Partner', 'Standard'],
    required: true,
  },
  {
    id: 'ef-4',
    entity: 'event',
    label: 'Meeting Conference Link',
    key: 'conference_link',
    type: 'text',
    required: false,
  },
];

export const initialFieldSets: FieldSets = {
  products: [
    'Cloud Data Platform Pro',
    'AI Workflow Suite',
    'Telematics Fleet Hub',
    'Enterprise Security Gateway',
    'Support & SLA Tier 1',
  ],
  dealStages: [
    { id: 'lead', name: 'Lead Qualified', probability: 20, color: '#64748b' },
    { id: 'discovery', name: 'Discovery & Needs', probability: 40, color: '#3b82f6' },
    { id: 'proposal', name: 'Proposal Sent', probability: 60, color: '#f59e0b' },
    { id: 'negotiation', name: 'Negotiation', probability: 80, color: '#8b5cf6' },
    { id: 'won', name: 'Closed Won', probability: 100, color: '#10b981' },
    { id: 'lost', name: 'Closed Lost', probability: 0, color: '#ef4444' },
  ],
  caseStatuses: ['New', 'Assigned', 'In Progress', 'Pending Customer', 'Resolved', 'Closed'],
  callOutcomes: [
    'Connected - Scheduled Demo',
    'Connected - Needs Follow-up',
    'Connected - Not Interested',
    'Left Voicemail',
    'Busy / No Answer',
    'Wrong Number',
  ],
  priorityLevels: ['Low', 'Medium', 'High', 'Critical'],
  industries: [
    'Enterprise Technology',
    'Healthcare & Life Sciences',
    'Logistics & Supply Chain',
    'Financial Services',
    'Manufacturing & Robotics',
    'Retail & E-commerce',
  ],
};

export const initialCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'CloudScale Networks',
    industry: 'Enterprise Technology',
    annualRevenue: 18500000,
    employeeCount: 210,
    phone: '+1 (415) 890-2345',
    website: 'https://cloudscalenetworks.example.com',
    billingAddress: '450 Mission St, San Francisco, CA 94105',
    shippingAddress: '450 Mission St, San Francisco, CA 94105',
    priority: 'High',
    ownerId: 'user-3',
    regionId: 'reg-1',
    description: 'High-growth multi-cloud infrastructure software provider expanding rapidly across US West.',
    isDefault: true,
    customFields: { vat_id: 'US-94-1827461', account_tier: 'Enterprise Plus' },
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-15T14:30:00Z',
  },
  {
    id: 'comp-2',
    name: 'BioVance Health Labs',
    industry: 'Healthcare & Life Sciences',
    annualRevenue: 34000000,
    employeeCount: 430,
    phone: '+1 (617) 555-8791',
    website: 'https://biovancehealth.example.com',
    billingAddress: '100 Binney St, Cambridge, MA 02142',
    shippingAddress: '100 Binney St, Cambridge, MA 02142',
    priority: 'Critical',
    ownerId: 'user-3',
    regionId: 'reg-2',
    description: 'Genomics and diagnostic data pipelines provider. Looking for secure compliant platform.',
    isDefault: false,
    customFields: { vat_id: 'US-04-9812734', account_tier: 'Enterprise Plus' },
    createdAt: '2026-08-14T11:00:00Z',
    updatedAt: '2026-09-14T09:20:00Z',
  },
  {
    id: 'comp-3',
    name: 'Nexus Logistics Group',
    industry: 'Logistics & Supply Chain',
    annualRevenue: 9800000,
    employeeCount: 120,
    phone: '+1 (312) 640-1920',
    website: 'https://nexuslogistics.example.com',
    billingAddress: '233 S Wacker Dr, Chicago, IL 60606',
    shippingAddress: '233 S Wacker Dr, Chicago, IL 60606',
    priority: 'Medium',
    ownerId: 'user-2',
    regionId: 'reg-1',
    description: 'Freight broker with automated dispatch network. Seeking fleet routing analytics.',
    isDefault: false,
    customFields: { vat_id: 'US-36-8172635', account_tier: 'Growth Tier' },
    createdAt: '2026-08-18T16:00:00Z',
    updatedAt: '2026-09-12T11:45:00Z',
  },
  {
    id: 'comp-4',
    name: 'FinEdge Wealth Advisory',
    industry: 'Financial Services',
    annualRevenue: 27000000,
    employeeCount: 180,
    phone: '+1 (212) 430-9988',
    website: 'https://finedgewealth.example.com',
    billingAddress: '388 Greenwich St, New York, NY 10013',
    shippingAddress: '388 Greenwich St, New York, NY 10013',
    priority: 'High',
    ownerId: 'user-3',
    regionId: 'reg-2',
    description: 'Institutional asset manager and advisory firm seeking enterprise-grade security gateway.',
    isDefault: false,
    customFields: { vat_id: 'US-13-4491029', account_tier: 'Strategic Partner' },
    createdAt: '2026-08-25T14:15:00Z',
    updatedAt: '2026-09-16T15:00:00Z',
  },
  {
    id: 'comp-5',
    name: 'Quantum Robotics Inc',
    industry: 'Manufacturing & Robotics',
    annualRevenue: 6200000,
    employeeCount: 65,
    phone: '+44 20 7946 0912',
    website: 'https://quantumrobotics.example.com',
    billingAddress: '25 Bank St, Canary Wharf, London E14 5JP',
    shippingAddress: '25 Bank St, Canary Wharf, London E14 5JP',
    priority: 'Medium',
    ownerId: 'user-4',
    regionId: 'reg-3',
    description: 'Precision robotic assembly units for cleanroom fabrication in Western Europe.',
    isDefault: false,
    customFields: { vat_id: 'GB-992-1082-34', account_tier: 'Standard' },
    createdAt: '2026-09-01T08:30:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
];

export const initialContacts: Contact[] = [
  {
    id: 'con-1',
    firstName: 'Marcus',
    lastName: 'Vance',
    email: 'm.vance@cloudscalenetworks.example.com',
    phone: '+1 (415) 890-2346',
    mobile: '+1 (415) 912-8811',
    jobTitle: 'VP of Technology & Infrastructure',
    messagingHandle: '@marcus_vance',
    mailingAddress: '450 Mission St, San Francisco, CA 94105',
    shippingAddress: '450 Mission St, San Francisco, CA 94105',
    ownerId: 'user-3',
    companyId: 'comp-1',
    type: 'customer',
    description: 'Primary decision maker for cloud data platform modernization. Preferred contact time: mornings.',
    campaignIds: ['camp-1'],
    customFields: { linkedin_url: 'https://linkedin.com/in/marcusvance-tech' },
    createdAt: '2026-08-11T09:15:00Z',
    updatedAt: '2026-09-15T15:00:00Z',
  },
  {
    id: 'con-2',
    firstName: 'Dr. Evelyn',
    lastName: 'Reed',
    email: 'ereed@biovancehealth.example.com',
    phone: '+1 (617) 555-8792',
    mobile: '+1 (617) 320-4491',
    jobTitle: 'Chief Medical Informatics Officer',
    messagingHandle: '@drevelynreed',
    mailingAddress: '100 Binney St, Cambridge, MA 02142',
    shippingAddress: '100 Binney St, Cambridge, MA 02142',
    ownerId: 'user-3',
    companyId: 'comp-2',
    type: 'lead',
    description: 'Interested in HIPAA-compliant diagnostic platform licensing. Needs legal data protection addendum.',
    campaignIds: ['camp-1'],
    customFields: { linkedin_url: 'https://linkedin.com/in/evelynreed-md' },
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-16T11:00:00Z',
  },
  {
    id: 'con-3',
    firstName: 'Carlos',
    lastName: 'Mendoza',
    email: 'cmendoza@nexuslogistics.example.com',
    phone: '+1 (312) 640-1921',
    mobile: '+1 (312) 710-8233',
    jobTitle: 'Director of Global Fleet Operations',
    messagingHandle: '@carlos_nexus',
    mailingAddress: '233 S Wacker Dr, Chicago, IL 60606',
    shippingAddress: '233 S Wacker Dr, Chicago, IL 60606',
    ownerId: 'user-2',
    companyId: 'comp-3',
    type: 'customer',
    description: 'Managed implementation of initial fleet telematics. Happy reference customer.',
    campaignIds: [],
    customFields: { linkedin_url: 'https://linkedin.com/in/carlosmendoza-ops' },
    createdAt: '2026-08-19T14:30:00Z',
    updatedAt: '2026-09-12T16:00:00Z',
  },
  {
    id: 'con-4',
    firstName: 'Rachel',
    lastName: 'Sterling',
    email: 'rsterling@finedgewealth.example.com',
    phone: '+1 (212) 430-9989',
    mobile: '+1 (917) 443-1288',
    jobTitle: 'Chief Information Security Officer',
    messagingHandle: '@rachel_sterling_sec',
    mailingAddress: '388 Greenwich St, New York, NY 10013',
    shippingAddress: '388 Greenwich St, New York, NY 10013',
    ownerId: 'user-3',
    companyId: 'comp-4',
    type: 'lead',
    description: 'Evaluating Enterprise Security Gateway for SEC/FINRA compliance standards.',
    campaignIds: ['camp-1'],
    customFields: { linkedin_url: 'https://linkedin.com/in/rachelsterling-ciso' },
    createdAt: '2026-08-26T11:30:00Z',
    updatedAt: '2026-09-16T14:10:00Z',
  },
  {
    id: 'con-5',
    firstName: 'James',
    lastName: 'Tanaka',
    email: 'j.tanaka@quantumrobotics.example.com',
    phone: '+44 20 7946 0914',
    mobile: '+44 7700 900341',
    jobTitle: 'Lead Robotics Software Architect',
    messagingHandle: '@jtanaka_robotics',
    mailingAddress: '25 Bank St, Canary Wharf, London E14 5JP',
    shippingAddress: '25 Bank St, Canary Wharf, London E14 5JP',
    ownerId: 'user-4',
    companyId: 'comp-5',
    type: 'lead',
    description: 'Requested technical documentation on AI Workflow Suite API integration.',
    campaignIds: [],
    customFields: { linkedin_url: 'https://linkedin.com/in/jamestanaka-robotics' },
    createdAt: '2026-09-02T13:45:00Z',
    updatedAt: '2026-09-14T10:00:00Z',
  },
  {
    id: 'con-6',
    firstName: 'Sophia',
    lastName: 'Lorenzi',
    email: 'sophia@lorenzi-procurement.example.com',
    phone: '+1 (206) 555-0149',
    mobile: '+1 (206) 555-0199',
    jobTitle: 'Strategic Procurement Advisor',
    messagingHandle: '@slorenzi',
    mailingAddress: '1201 3rd Ave, Seattle, WA 98101',
    shippingAddress: '1201 3rd Ave, Seattle, WA 98101',
    ownerId: 'user-1',
    type: 'vendor',
    description: 'Independent advisor facilitating vendor selection for Pacific Northwest enterprises.',
    campaignIds: [],
    customFields: { linkedin_url: 'https://linkedin.com/in/sophialorenzi' },
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-05T09:00:00Z',
  },
];

export const initialDeals: Deal[] = [
  {
    id: 'deal-1',
    title: 'CloudScale Enterprise Cloud Data Platform',
    companyId: 'comp-1',
    contactId: 'con-1',
    product: 'Cloud Data Platform Pro',
    value: 120000,
    currency: 'USD',
    stage: 'proposal',
    status: 'open',
    expectedCloseDate: '2026-10-15',
    nextStep: 'Present finalized security and architecture blueprint with executive sponsor',
    ownerId: 'user-3',
    description: 'Multi-year deployment for 180 engineers with automated schema migrations and HA failover.',
    targetId: 'tar-1',
    history: [
      { timestamp: '2026-08-12T10:00:00Z', actor: 'Alex Rivera', action: 'Created deal in Lead Qualified' },
      { timestamp: '2026-08-28T14:30:00Z', actor: 'Alex Rivera', action: 'Moved to Discovery & Needs', fromStage: 'lead', toStage: 'discovery' },
      { timestamp: '2026-09-10T16:00:00Z', actor: 'Alex Rivera', action: 'Moved to Proposal Sent', fromStage: 'discovery', toStage: 'proposal', note: 'Sent v2 proposal quoting $120k ARR' },
    ],
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-09-10T16:00:00Z',
  },
  {
    id: 'deal-2',
    title: 'BioVance Diagnostic Platform AI Licensing',
    companyId: 'comp-2',
    contactId: 'con-2',
    product: 'AI Workflow Suite',
    value: 245000,
    currency: 'USD',
    stage: 'negotiation',
    status: 'open',
    expectedCloseDate: '2026-09-30',
    nextStep: 'Complete legal review of Business Associate Agreement (BAA)',
    ownerId: 'user-3',
    description: 'High-margin AI diagnostic engine deployment. In final terms discussion.',
    targetId: 'tar-1',
    history: [
      { timestamp: '2026-08-16T11:00:00Z', actor: 'Alex Rivera', action: 'Created deal' },
      { timestamp: '2026-09-02T15:00:00Z', actor: 'Alex Rivera', action: 'Moved to Proposal Sent', fromStage: 'discovery', toStage: 'proposal' },
      { timestamp: '2026-09-14T10:15:00Z', actor: 'Alex Rivera', action: 'Moved to Negotiation', fromStage: 'proposal', toStage: 'negotiation', note: 'Discount locked at 8% with 3-year term' },
    ],
    createdAt: '2026-08-16T11:00:00Z',
    updatedAt: '2026-09-14T10:15:00Z',
  },
  {
    id: 'deal-3',
    title: 'Nexus Fleet Telematics Integration',
    companyId: 'comp-3',
    contactId: 'con-3',
    product: 'Telematics Fleet Hub',
    value: 58000,
    currency: 'USD',
    stage: 'won',
    status: 'won',
    expectedCloseDate: '2026-09-10',
    nextStep: 'Onboarding kickoff completed. Handed off to Customer Success.',
    ownerId: 'user-2',
    description: 'Connected 120 long-haul trucks with live GPS telematics and driver safety alerts.',
    targetId: 'tar-1',
    history: [
      { timestamp: '2026-08-20T09:00:00Z', actor: 'David Ross', action: 'Created deal' },
      { timestamp: '2026-09-01T11:00:00Z', actor: 'David Ross', action: 'Moved to Negotiation' },
      { timestamp: '2026-09-10T17:00:00Z', actor: 'David Ross', action: 'Closed Won deal', fromStage: 'negotiation', toStage: 'won', note: 'Contracts signed via DocuSign' },
    ],
    createdAt: '2026-08-20T09:00:00Z',
    updatedAt: '2026-09-10T17:00:00Z',
  },
  {
    id: 'deal-4',
    title: 'FinEdge Security Gateway Implementation',
    companyId: 'comp-4',
    contactId: 'con-4',
    product: 'Enterprise Security Gateway',
    value: 85000,
    currency: 'USD',
    stage: 'discovery',
    status: 'open',
    expectedCloseDate: '2026-11-20',
    nextStep: 'Schedule technical deep dive on SOC2 Type II and pen-test results',
    ownerId: 'user-3',
    description: 'Evaluation of zero-trust gateway for wealth advisors accessing portfolio databases.',
    targetId: 'tar-1',
    history: [
      { timestamp: '2026-08-27T10:00:00Z', actor: 'Alex Rivera', action: 'Created deal' },
      { timestamp: '2026-09-05T14:00:00Z', actor: 'Alex Rivera', action: 'Moved to Discovery', fromStage: 'lead', toStage: 'discovery' },
    ],
    createdAt: '2026-08-27T10:00:00Z',
    updatedAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'deal-5',
    title: 'Quantum Robotics Vision Workflow Suite',
    companyId: 'comp-5',
    contactId: 'con-5',
    product: 'AI Workflow Suite',
    value: 45000,
    currency: 'USD',
    stage: 'lead',
    status: 'open',
    expectedCloseDate: '2026-12-05',
    nextStep: 'Follow up on technical feasibility whitepaper download',
    ownerId: 'user-4',
    description: 'Robotic arm optical defect inspection pipeline.',
    history: [
      { timestamp: '2026-09-04T12:00:00Z', actor: 'Elena Rostova', action: 'Created deal from inbound website inquiry' },
    ],
    createdAt: '2026-09-04T12:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Send revised BAA contract terms to BioVance legal team',
    deadline: '2026-09-18',
    status: 'In Progress',
    completionPercentage: 70,
    assigneeId: 'user-3',
    companyId: 'comp-2',
    contactId: 'con-2',
    description: 'Coordinate with internal legal on Section 4 indemnification clause before dispatching.',
    history: [
      { timestamp: '2026-09-15T09:00:00Z', actor: 'Alex Rivera', oldPercent: 0, newPercent: 40, oldStatus: 'Not Started', newStatus: 'In Progress', note: 'Draft received from legal' },
      { timestamp: '2026-09-16T15:00:00Z', actor: 'Alex Rivera', oldPercent: 40, newPercent: 70, oldStatus: 'In Progress', newStatus: 'In Progress', note: 'Incorporated Dr. Reed comments' },
    ],
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-16T15:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Prepare executive architecture slide deck for CloudScale demo',
    deadline: '2026-09-19',
    status: 'In Progress',
    completionPercentage: 50,
    assigneeId: 'user-3',
    companyId: 'comp-1',
    contactId: 'con-1',
    description: 'Outline hybrid cloud sync topologies and backup failover benchmarks.',
    history: [
      { timestamp: '2026-09-16T10:00:00Z', actor: 'Alex Rivera', oldPercent: 0, newPercent: 50, oldStatus: 'Not Started', newStatus: 'In Progress' },
    ],
    createdAt: '2026-09-16T10:00:00Z',
    updatedAt: '2026-09-16T10:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Execute Q3 sales target performance review with regional team',
    deadline: '2026-09-22',
    status: 'Not Started',
    completionPercentage: 0,
    assigneeId: 'user-2',
    description: 'Review attainment against $450k team quarterly revenue goal.',
    history: [],
    createdAt: '2026-09-14T08:00:00Z',
    updatedAt: '2026-09-14T08:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Resolve high priority API rate limiting ticket for CloudScale',
    deadline: '2026-09-17',
    status: 'In Progress',
    completionPercentage: 80,
    assigneeId: 'user-4',
    companyId: 'comp-1',
    description: 'Increase production cluster egress burst limits to 5,000 req/min.',
    history: [],
    createdAt: '2026-09-17T08:00:00Z',
    updatedAt: '2026-09-17T09:30:00Z',
  },
  {
    id: 'task-5',
    title: 'Follow up with FinEdge compliance officer regarding audit logs',
    deadline: '2026-09-16', // overdue
    status: 'Not Started',
    completionPercentage: 0,
    assigneeId: 'user-3',
    companyId: 'comp-4',
    contactId: 'con-4',
    description: 'Provide cryptographic checksum specification for archive export verification.',
    history: [],
    createdAt: '2026-09-13T11:00:00Z',
    updatedAt: '2026-09-13T11:00:00Z',
  },
];

export const initialCases: Case[] = [
  {
    id: 'case-1',
    title: 'Inbound Webhook latency degradation during peak traffic',
    problemName: 'Slow webhook response (>1.8s) causing client timeouts',
    status: 'In Progress',
    priority: 'Critical',
    ownerId: 'user-4',
    companyId: 'comp-1',
    contactId: 'con-1',
    description: 'CloudScale ingest pipeline reported dropped webhook packets between 14:00 - 15:30 UTC yesterday.',
    teamMemberIds: ['user-4', 'user-1'],
    internalNotes: [
      { id: 'cn-1', author: 'Elena Rostova', text: 'Identified connection pool exhaustion on replica DB. Patching worker pool size.', createdAt: '2026-09-16T16:00:00Z' },
      { id: 'cn-2', author: 'Sarah Jenkins', text: 'Confirmed load balancer retry policy tuned. Monitoring live latency.', createdAt: '2026-09-17T07:15:00Z' },
    ],
    createdAt: '2026-09-16T15:40:00Z',
    updatedAt: '2026-09-17T07:15:00Z',
  },
  {
    id: 'case-2',
    title: 'Telematics GPS heartbeat discrepancy on fleet unit #42',
    problemName: 'Cellular modem packet loss in mountainous route',
    status: 'Resolved',
    priority: 'Medium',
    ownerId: 'user-4',
    companyId: 'comp-3',
    contactId: 'con-3',
    description: 'Nexus vehicle 42 lost tracking ping for 45 minutes on I-70 corridor.',
    closedDate: '2026-09-15',
    teamMemberIds: ['user-4'],
    internalNotes: [
      { id: 'cn-3', author: 'Elena Rostova', text: 'Firmware updated to store-and-forward offline buffer mode. Verified sync on reconnection.', createdAt: '2026-09-15T14:00:00Z' },
    ],
    createdAt: '2026-09-14T11:00:00Z',
    updatedAt: '2026-09-15T14:30:00Z',
  },
  {
    id: 'case-3',
    title: 'Custom export delimiter rendering issue in legacy spreadsheet',
    problemName: 'Tab delimited exports enclosed quotes unexpectedly',
    status: 'New',
    priority: 'Low',
    ownerId: 'user-4',
    companyId: 'comp-5',
    contactId: 'con-5',
    description: 'Client is using an older spreadsheet macro expecting unquoted tab separation.',
    teamMemberIds: ['user-4'],
    internalNotes: [],
    createdAt: '2026-09-17T06:30:00Z',
    updatedAt: '2026-09-17T06:30:00Z',
  },
];

export const initialEvents: Event[] = [
  {
    id: 'evt-1',
    title: 'CloudScale Architecture Review & Security Briefing',
    startDate: '2026-09-17',
    startTime: '10:00',
    endDate: '2026-09-17',
    endTime: '11:00',
    participantIds: ['user-3', 'user-1'],
    confirmed: true,
    companyId: 'comp-1',
    contactId: 'con-1',
    location: 'Video Conference / Room 4B',
    directions: 'Google Meet link in calendar invitation',
    notes: 'Cover data retention, multi-tenant isolation, and automated failover guarantees.',
    emailAlert: true,
    ownerId: 'user-3',
    createdAt: '2026-09-12T14:00:00Z',
    updatedAt: '2026-09-12T14:00:00Z',
  },
  {
    id: 'evt-2',
    title: 'BioVance BAA Contract & Legal Terms Finalization',
    startDate: '2026-09-18',
    startTime: '14:00',
    endDate: '2026-09-18',
    endTime: '15:00',
    participantIds: ['user-3', 'user-2'],
    confirmed: true,
    companyId: 'comp-2',
    contactId: 'con-2',
    location: 'Executive Zoom Boardroom',
    directions: 'Meeting passcode sent via secure channel',
    notes: 'Walk through Section 4 indemnity with Dr. Reed and general counsel.',
    emailAlert: true,
    ownerId: 'user-3',
    createdAt: '2026-09-14T16:00:00Z',
    updatedAt: '2026-09-14T16:00:00Z',
  },
  {
    id: 'evt-3',
    title: 'Weekly Sales Pipeline & Target Review',
    startDate: '2026-09-19',
    startTime: '09:00',
    endDate: '2026-09-19',
    endTime: '10:00',
    participantIds: ['user-1', 'user-2', 'user-3', 'user-4'],
    confirmed: true,
    location: 'Main Conference Hall & Remote Sync',
    notes: 'Review month-to-date deals won, stalled negotiations, and outreach campaigns.',
    emailAlert: true,
    ownerId: 'user-2',
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-10T10:00:00Z',
  },
];

export const initialCallScripts: CallScript[] = [
  {
    id: 'script-1',
    name: 'Enterprise Discovery & Qualification Script',
    description: 'Standard 4-question script used by sales reps during initial qualification calls.',
    elements: [
      {
        id: 'el-1',
        type: 'instruction',
        prompt: 'Warmly introduce yourself and confirm if now is still a convenient time for a 10-minute discovery call.',
      },
      {
        id: 'el-2',
        type: 'yes_no',
        prompt: 'Is the organization actively budgeting for a cloud data modernization project this calendar year?',
      },
      {
        id: 'el-3',
        type: 'multiple_choice',
        prompt: 'What is their primary architectural driver?',
        options: ['Security & Compliance (SOC2/HIPAA)', 'Scale & Multi-region latency', 'Cost optimization', 'Developer ergonomics'],
      },
      {
        id: 'el-4',
        type: 'free_text',
        prompt: 'Key requirements and agreed next action items:',
      },
    ],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'script-2',
    name: 'Support Ticket Escalation Check',
    description: 'Support rep checklist for verifying customer urgency and reproducing system incidents.',
    elements: [
      {
        id: 'el-21',
        type: 'instruction',
        prompt: 'Express empathy for the interruption and assure client of our tier-1 priority support handling.',
      },
      {
        id: 'el-22',
        type: 'yes_no',
        prompt: 'Is production data traffic currently being impacted or degraded?',
      },
      {
        id: 'el-23',
        type: 'multiple_choice',
        prompt: 'Severity Level Classification:',
        options: ['P1 - Outage (All users blocked)', 'P2 - Degraded Performance', 'P3 - Minor bug / workaround available', 'P4 - General inquiry'],
      },
      {
        id: 'el-24',
        type: 'free_text',
        prompt: 'Steps taken to reproduce and customer engineer contact on standby:',
      },
    ],
    createdAt: '2026-08-05T00:00:00Z',
  },
];

export const initialCalls: Call[] = [
  {
    id: 'call-1',
    subject: 'Follow up on BioVance AI license terms with Dr. Reed',
    date: '2026-09-17',
    time: '11:30',
    direction: 'outbound',
    outcomeStatus: 'Pending',
    companyId: 'comp-2',
    contactId: 'con-2',
    assignedUserId: 'user-3',
    notes: 'Check if legal counsel had any reservations regarding indemnification limits.',
    scriptId: 'script-1',
    isScheduled: true,
    isCompleted: false,
    createdAt: '2026-09-16T14:00:00Z',
    updatedAt: '2026-09-16T14:00:00Z',
  },
  {
    id: 'call-2',
    subject: 'Immediate introductory call: Rachel Sterling (FinEdge)',
    date: '2026-09-17',
    time: '09:00',
    direction: 'outbound',
    outcomeStatus: 'Pending',
    companyId: 'comp-4',
    contactId: 'con-4',
    assignedUserId: 'user-3',
    notes: 'Qualify timeline for security audit deployment before end of Q4.',
    scriptId: 'script-1',
    isScheduled: false,
    isCompleted: false,
    createdAt: '2026-09-17T07:30:00Z',
    updatedAt: '2026-09-17T07:30:00Z',
  },
  {
    id: 'call-3',
    subject: 'Cold inbound inquiry: Mark Lindqvist (Nordic Tech)',
    date: '2026-09-17',
    time: '08:45',
    direction: 'inbound',
    outcomeStatus: 'Pending',
    externalName: 'Mark Lindqvist',
    externalPhone: '+46 8 123 4567',
    assignedUserId: 'user-3',
    notes: 'Interested in API Workflow Suite pricing tiers for 50 users.',
    scriptId: 'script-1',
    isScheduled: false,
    isCompleted: false,
    createdAt: '2026-09-17T07:45:00Z',
    updatedAt: '2026-09-17T07:45:00Z',
  },
  {
    id: 'call-4',
    subject: 'Discovery check-in with Marcus Vance',
    date: '2026-09-15',
    time: '14:00',
    direction: 'outbound',
    outcomeStatus: 'Connected - Scheduled Demo',
    companyId: 'comp-1',
    contactId: 'con-1',
    assignedUserId: 'user-3',
    notes: 'Discussed architectural fit. Marcus scheduled architecture review meeting for 17th.',
    durationSeconds: 740,
    scriptId: 'script-1',
    scriptAnswers: {
      'el-2': 'Yes',
      'el-3': 'Security & Compliance (SOC2/HIPAA)',
      'el-4': 'Budget is approved for $120k ARR. Demo planned with core engineering leads.',
    },
    isScheduled: true,
    isCompleted: true,
    createdAt: '2026-09-15T14:00:00Z',
    updatedAt: '2026-09-15T14:15:00Z',
  },
  {
    id: 'call-5',
    subject: 'Scheduled check with Carlos Mendoza',
    date: '2026-09-18',
    time: '15:30',
    direction: 'outbound',
    outcomeStatus: 'Pending',
    companyId: 'comp-3',
    contactId: 'con-3',
    assignedUserId: 'user-2',
    notes: 'Check satisfaction with telematics firmware fix deployed this week.',
    isScheduled: true,
    isCompleted: false,
    createdAt: '2026-09-16T11:00:00Z',
    updatedAt: '2026-09-16T11:00:00Z',
  },
];

export const initialTargets: Target[] = [
  {
    id: 'tar-1',
    name: 'Q3 Enterprise Revenue Target',
    type: 'revenue',
    goalValue: 450000,
    period: 'quarter',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    assignedUserIds: ['user-2', 'user-3'],
    createdAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'tar-2',
    name: 'September Customer Cases Resolved',
    type: 'cases_resolved',
    goalValue: 25,
    period: 'month',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    assignedUserIds: ['user-4'],
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'tar-3',
    name: 'Q3 AI Workflow Units Closed',
    type: 'units_sold',
    goalValue: 12,
    period: 'quarter',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    assignedUserIds: ['user-3', 'user-4'],
    createdAt: '2026-07-01T00:00:00Z',
  },
];

export const initialFolders: Folder[] = [
  { id: 'fld-root', name: 'Root Folder', description: 'Master CRM repository', parentId: null },
  { id: 'fld-sales', name: 'Sales Collateral & Proposals', description: 'Decks, pricing sheets, case studies', parentId: 'fld-root' },
  { id: 'fld-legal', name: 'Legal Agreements & BAAs', description: 'Standard MSA, NDAs, HIPAA agreements', parentId: 'fld-root' },
  { id: 'fld-clients', name: 'Client Shared Folders', description: 'Dedicated documentation per company', parentId: 'fld-root' },
];

export const initialDocuments: DocumentFile[] = [
  {
    id: 'doc-1',
    title: 'Apex Cloud Platform Architecture Whitepaper',
    description: 'Technical overview of zero-trust microservice architecture and fault tolerance.',
    version: '2.4',
    folderId: 'fld-sales',
    fileName: 'Apex_Architecture_Whitepaper_v2.4.pdf',
    fileSize: 3450000,
    fileType: 'application/pdf',
    companyId: 'comp-1',
    uploadedBy: 'Sarah Jenkins',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-02T14:00:00Z',
  },
  {
    id: 'doc-2',
    title: 'Standard HIPAA Business Associate Agreement (BAA)',
    description: 'Updated template compliant with HITECH and HHS enforcement rules.',
    version: '1.2',
    folderId: 'fld-legal',
    fileName: 'Apex_BAA_Agreement_Template.docx',
    fileSize: 890000,
    fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    companyId: 'comp-2',
    uploadedBy: 'David Ross',
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-09-14T09:00:00Z',
  },
  {
    id: 'doc-3',
    title: 'Telematics Fleet Gateway Installation Manual',
    description: 'Hardware wiring schematics and OBD-II pairing guide for vehicle technicians.',
    version: '3.0',
    folderId: 'fld-clients',
    fileName: 'Nexus_Telematics_Manual_v3.pdf',
    fileSize: 5200000,
    fileType: 'application/pdf',
    companyId: 'comp-3',
    uploadedBy: 'Elena Rostova',
    createdAt: '2026-09-01T15:00:00Z',
    updatedAt: '2026-09-01T15:00:00Z',
  },
];

export const initialEmailAccounts: EmailAccount[] = [
  {
    id: 'ea-1',
    name: 'Apex Sales Sync Mailbox',
    email: 'sales@apexsolutions.example.com',
    provider: 'Google Workspace',
    status: 'connected',
    lastSyncedAt: '2026-09-17T07:25:00Z',
  },
  {
    id: 'ea-2',
    name: 'Support Operations Mailbox',
    email: 'support@apexsolutions.example.com',
    provider: 'Microsoft 365',
    status: 'connected',
    lastSyncedAt: '2026-09-17T07:10:00Z',
  },
];

export const initialEmailMessages: EmailMessage[] = [
  {
    id: 'em-1',
    accountId: 'ea-1',
    subject: 'Re: CloudScale - Security Questionnaire response & next steps',
    sender: 'm.vance@cloudscalenetworks.example.com',
    recipient: 'sales@apexsolutions.example.com',
    body: 'Hi Alex, our SecOps lead reviewed your responses and was pleased with the multi-region failover benchmarks. Looking forward to our call this Thursday at 10 AM.',
    timestamp: '2026-09-16T18:24:00Z',
    attachedTo: {
      type: 'contact',
      id: 'con-1',
      name: 'Marcus Vance',
    },
  },
  {
    id: 'em-2',
    accountId: 'ea-1',
    subject: 'BioVance Contract - Section 4 redline comments',
    sender: 'ereed@biovancehealth.example.com',
    recipient: 'sales@apexsolutions.example.com',
    body: 'Alex, attached are our internal legal counsel markups on the BAA. The primary point is around audit notification windows. Can we discuss on Friday?',
    timestamp: '2026-09-16T14:15:00Z',
    attachedTo: {
      type: 'company',
      id: 'comp-2',
      name: 'BioVance Health Labs',
    },
  },
  {
    id: 'em-3',
    accountId: 'ea-2',
    subject: 'Case #CASE-1 Inbound webhook latency notice',
    sender: 'ops@cloudscalenetworks.example.com',
    recipient: 'support@apexsolutions.example.com',
    body: 'We noticed response times spiked above 1800ms between 14:00 - 15:30. Opening ticket for urgent review.',
    timestamp: '2026-09-16T15:35:00Z',
    attachedTo: {
      type: 'case',
      id: 'case-1',
      name: 'Inbound Webhook latency degradation',
    },
  },
];

export const initialEmailTemplates: EmailTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Executive Discovery Follow-up',
    subject: 'Following up on our discussion regarding {{company.name}}',
    body: `Hello {{contact.firstName}},

Thank you for taking the time to speak with me earlier today. Based on our conversation regarding {{company.name}}, I've assembled the architecture overview and pricing details for your review.

Please let me know if you would like to schedule a 30-minute technical session with our solution architects next week.

Warm regards,
{{user.name}}
{{user.email}}
Apex Global Solutions`,
    createdAt: '2026-08-10T00:00:00Z',
  },
  {
    id: 'tmpl-2',
    name: 'New Product Announcement - AI Workflow Suite',
    subject: 'Accelerate your operations with the new AI Workflow Suite',
    body: `Hi {{contact.firstName}},

We are thrilled to announce the launch of our next-generation AI Workflow Suite, purpose-built to streamline data transformation and compliance audits for leaders in {{company.industry}}.

Click here to explore the interactive sandbox or book a personalized demonstration.

Best,
The Apex Solutions Team`,
    createdAt: '2026-08-15T00:00:00Z',
  },
];

export const initialCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    title: 'Q3 Enterprise Cloud Modernization Outreach',
    schedule: 'one-off',
    templateId: 'tmpl-2',
    sendingAccountId: 'ea-1',
    status: 'sent',
    sentCount: 148,
    openedCount: 92,
    clickedCount: 44,
    bouncedCount: 2,
    recipientContactIds: ['con-1', 'con-2', 'con-4'],
    sentAt: '2026-09-12T14:00:00Z',
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'camp-2',
    title: 'Automated Post-Support Case Satisfaction Survey',
    schedule: 'recurring',
    templateId: 'tmpl-1',
    sendingAccountId: 'ea-2',
    status: 'scheduled',
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    bouncedCount: 0,
    recipientContactIds: ['con-3'],
    createdAt: '2026-09-15T11:00:00Z',
  },
];

export const initialCustomForms: CustomForm[] = [
  {
    id: 'form-1',
    title: 'Enterprise Technical Qualification & Needs Intake',
    description: 'Intake form for new prospective client technical architects and procurement teams.',
    instructions: 'Please answer the following questions to help our solution team size your implementation.',
    isPublic: true,
    questions: [
      { id: 'q-1', prompt: 'What is your primary cloud platform provider?', type: 'multiple_choice', options: ['AWS', 'Google Cloud', 'Microsoft Azure', 'On-premises / Hybrid'], required: true },
      { id: 'q-2', prompt: 'Estimated monthly active transactions or records:', type: 'free_text', required: true },
      { id: 'q-3', prompt: 'Do you require dedicated HIPAA or SOC2 Type II compliance validation?', type: 'yes_no', required: true },
      { id: 'q-4', prompt: 'Target implementation go-live date:', type: 'date', required: false },
    ],
    submissions: [
      {
        id: 'sub-1',
        contactId: 'con-1',
        responderName: 'Marcus Vance',
        responderEmail: 'm.vance@cloudscalenetworks.example.com',
        answers: {
          'q-1': 'Google Cloud',
          'q-2': '25 Million records/month',
          'q-3': 'Yes',
          'q-4': '2026-10-15',
        },
        submittedAt: '2026-09-12T16:20:00Z',
      },
    ],
    createdAt: '2026-08-20T00:00:00Z',
  },
];

export const initialMessageThreads: MessageThread[] = [
  {
    id: 'msg-1',
    title: 'Q3 Closing Sprint: Target Attainment & Celebration',
    content: 'Team, with our Nexus deal won and BioVance in final contract negotiations, we are at 67% of our quarterly revenue target with two weeks remaining. Let us keep the momentum high and clear remaining customer verification roadblocks!',
    authorId: 'user-2',
    authorName: 'David Ross',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-15T09:00:00Z',
    replies: [
      {
        id: 'rep-1',
        authorId: 'user-3',
        authorName: 'Alex Rivera',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        text: 'CloudScale presentation deck is looking great too! If we close both BioVance and CloudScale, we exceed 100% of goal.',
        createdAt: '2026-09-15T09:30:00Z',
      },
      {
        id: 'rep-2',
        authorId: 'user-1',
        authorName: 'Sarah Jenkins',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        text: 'Awesome execution everyone. Let me know if you need any executive sponsorship on either call this week.',
        createdAt: '2026-09-15T10:15:00Z',
      },
    ],
  },
  {
    id: 'msg-2',
    title: 'Updated Call Scripts & Compliance Guidance for Financial Accounts',
    content: 'We updated Script #1 to include compliance questions regarding SEC/FINRA log encryption. Please review before dialing FinEdge or wealth advisory leads.',
    authorId: 'user-1',
    authorName: 'Sarah Jenkins',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-14T11:00:00Z',
    replies: [],
  },
];

export const initialDirectMessages: DirectMessage[] = [
  {
    id: 'dm-1',
    senderId: 'user-3',
    senderName: 'Alex Rivera',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-1',
    recipientName: 'Sarah Jenkins',
    recipientAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    text: 'Hi Sarah, Dr. Evelyn Reed at BioVance requested an updated BAA clause for the diagnostic AI license. Are we cleared to issue the revised addendum?',
    createdAt: '2026-09-16T14:15:00Z',
    read: true,
    relatedRecord: {
      type: 'deal',
      id: 'deal-2',
      title: 'BioVance Diagnostic Platform AI Licensing',
    },
  },
  {
    id: 'dm-2',
    senderId: 'user-1',
    senderName: 'Sarah Jenkins',
    senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-3',
    recipientName: 'Alex Rivera',
    recipientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    text: 'Yes, approved! Use the standard tier-2 compliance addendum from Documents. Ping me if you need executive sponsorship during their legal signoff.',
    createdAt: '2026-09-16T14:22:00Z',
    read: true,
  },
  {
    id: 'dm-3',
    senderId: 'user-3',
    senderName: 'Alex Rivera',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-1',
    recipientName: 'Sarah Jenkins',
    recipientAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    text: 'Awesome, sent the packet over to Dr. Reed and scheduled our confirmation call.',
    createdAt: '2026-09-16T14:40:00Z',
    read: true,
  },
  {
    id: 'dm-4',
    senderId: 'user-2',
    senderName: 'David Ross',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-4',
    recipientName: 'Elena Rostova',
    recipientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    text: 'Hi Elena, how is the onboarding going for CloudScale Networks? Did they configure their telemetry webhook endpoints?',
    createdAt: '2026-09-17T09:10:00Z',
    read: true,
    relatedRecord: {
      type: 'company',
      id: 'comp-1',
      title: 'CloudScale Networks',
    },
  },
  {
    id: 'dm-5',
    senderId: 'user-4',
    senderName: 'Elena Rostova',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-2',
    recipientName: 'David Ross',
    recipientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    text: 'Hey David! Marcus Vance confirmed their engineering team finished testing the staging endpoint. All green for production rollout next Tuesday!',
    createdAt: '2026-09-17T09:35:00Z',
    read: false,
  },
  {
    id: 'dm-6',
    senderId: 'user-2',
    senderName: 'David Ross',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-1',
    recipientName: 'Sarah Jenkins',
    recipientAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    text: 'Sarah, let us review the regional targets for NA-East this afternoon before the weekly pipeline review.',
    createdAt: '2026-09-17T11:00:00Z',
    read: true,
  },
];

export const initialSharedResources: SharedResource[] = [
  {
    id: 'res-1',
    title: 'Official SEC Rule 17a-4 Electronic Records Compliance Checklist',
    type: 'link',
    url: 'https://www.sec.gov/rules/final/34-47806.htm',
    createdBy: 'Sarah Jenkins',
    createdAt: '2026-08-10T12:00:00Z',
  },
  {
    id: 'res-2',
    title: 'Sales Objection Handling Playbook for Cloud Migrations',
    type: 'note',
    body: `Top 3 Objections:
1. "We already use native AWS/GCP tools": Emphasize unified multi-cloud audit posture and reduced vendor lock-in.
2. "Timeline is too long": Highlight our 14-day automated zero-downtime pilot program.
3. "Security sign-off": Provide our pre-filled SIG Lite and SOC2 Type II report immediate packet.`,
    createdBy: 'David Ross',
    createdAt: '2026-08-18T15:00:00Z',
  },
  {
    id: 'res-3',
    title: 'Global Fleet Telematics Sensor Hardware Catalog',
    type: 'link',
    url: 'https://telematics-standards.example.com/sensors-2026',
    createdBy: 'Elena Rostova',
    createdAt: '2026-09-02T10:00:00Z',
  },
];

export const initialAuditLogs: AuditLogItem[] = [
  {
    id: 'log-1',
    actorId: 'user-1',
    actorName: 'Sarah Jenkins',
    action: 'ORGANISATION_SETUP',
    details: 'Configured organisation profile and set global sharing policy to all_shared',
    timestamp: '2026-08-01T08:00:00Z',
  },
  {
    id: 'log-2',
    actorId: 'user-1',
    actorName: 'Sarah Jenkins',
    action: 'USER_CREATED',
    details: 'Provisioned user accounts for David Ross (Manager) and Alex Rivera (Standard)',
    timestamp: '2026-08-01T09:30:00Z',
  },
  {
    id: 'log-3',
    actorId: 'user-2',
    actorName: 'David Ross',
    action: 'TARGET_CREATED',
    details: 'Created target "Q3 Enterprise Revenue Target" ($450,000 goal)',
    timestamp: '2026-07-01T10:00:00Z',
  },
  {
    id: 'log-4',
    actorId: 'user-3',
    actorName: 'Alex Rivera',
    action: 'DEAL_UPDATED',
    details: 'Moved "BioVance Diagnostic Platform AI Licensing" to Negotiation stage',
    timestamp: '2026-09-14T10:15:00Z',
  },
  {
    id: 'log-5',
    actorId: 'user-1',
    actorName: 'Sarah Jenkins',
    action: 'BULK_EXPORT',
    details: 'Exported 14 records from Companies and Contacts combined (CSV, comma-delimited)',
    timestamp: '2026-09-16T17:00:00Z',
  },
];

export const initialSavedViews: SavedCustomView[] = [
  // Company Views
  {
    id: 'view-comp-all',
    title: 'All Companies',
    module: 'company',
    entity: 'company',
    columns: ['name', 'industry', 'priority', 'owner', 'phone', 'city'],
    filters: {},
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'Complete overview of all active organisation accounts and clients.',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'view-comp-active',
    title: 'Active Companies',
    module: 'company',
    entity: 'company',
    columns: ['name', 'industry', 'phone', 'email', 'city', 'priority'],
    filters: {
      status: 'Active',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'Companies with active relationships across high, medium, and critical tiers.',
    createdAt: '2026-08-02T09:00:00Z',
    updatedAt: '2026-08-02T09:00:00Z',
  },
  {
    id: 'view-comp-key-accounts',
    title: 'High Priority Accounts',
    module: 'company',
    entity: 'company',
    columns: ['name', 'industry', 'annualRevenue', 'priority', 'owner', 'phone', 'city'],
    filters: {
      priority: 'High',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: false,
    description: 'Tier-1 enterprise accounts with high and critical engagement urgency.',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'view-comp-tech',
    title: 'Technology Sector',
    module: 'company',
    entity: 'company',
    columns: ['name', 'industry', 'phone', 'email', 'website', 'city'],
    filters: {
      industry: 'Enterprise Technology',
    },
    userId: 'user-2',
    userName: 'David Ross',
    isShared: true,
    isSystem: false,
    description: 'Enterprise tech and software infrastructure prospects and clients.',
    createdAt: '2026-08-15T11:00:00Z',
    updatedAt: '2026-08-15T11:00:00Z',
  },

  // Contact / Lead / Customer Views
  {
    id: 'view-con-all',
    title: 'All Contacts',
    module: 'contact',
    entity: 'contact',
    columns: ['name', 'company', 'type', 'email', 'phone', 'owner'],
    filters: {},
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'Directory of all people across leads, customers, vendors, and contacts.',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'view-con-leads',
    title: 'Important Leads',
    module: 'contact',
    entity: 'contact',
    columns: ['name', 'jobTitle', 'company', 'email', 'phone', 'type', 'owner'],
    filters: {
      type: 'lead',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'Prospective decision makers and leads currently being qualified.',
    createdAt: '2026-08-05T09:30:00Z',
    updatedAt: '2026-08-05T09:30:00Z',
  },
  {
    id: 'view-con-customers',
    title: 'My Customers',
    module: 'contact',
    entity: 'contact',
    columns: ['name', 'jobTitle', 'company', 'email', 'phone', 'owner'],
    filters: {
      type: 'customer',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: false,
    description: 'Active client accounts and executive customer contacts.',
    createdAt: '2026-08-12T14:00:00Z',
    updatedAt: '2026-08-12T14:00:00Z',
  },

  // Deal Views
  {
    id: 'view-deal-pipeline',
    title: 'Active Pipeline Deals',
    module: 'deal',
    columns: ['title', 'company', 'value', 'stage', 'status', 'expectedCloseDate', 'owner'],
    filters: {
      status: 'open',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'All currently open sales opportunities moving through the pipeline.',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'view-deal-high-value',
    title: 'High Value Deals ($100k+)',
    module: 'deal',
    columns: ['title', 'company', 'product', 'value', 'stage', 'owner'],
    filters: {
      status: 'open',
    },
    userId: 'user-2',
    userName: 'David Ross',
    isShared: true,
    isSystem: false,
    description: 'Major sales opportunities exceeding standard contract thresholds.',
    createdAt: '2026-08-20T16:00:00Z',
    updatedAt: '2026-08-20T16:00:00Z',
  },
];
