import {
  Organisation,
  User,
  Region,
  ExtendedField,
  FieldSets,
  Company,
  Contact,
  Deal,
  Task,
  Case,
  Event,
  Call,
  CallScript,
  Target,
  Folder,
  DocumentFile,
  EmailAccount,
  EmailMessage,
  EmailTemplate,
  Campaign,
  CustomForm,
  MessageThread,
  DirectMessage,
  SharedResource,
  AuditLogItem,
  SavedCustomView,
  CRMNotification,
  MeetingTemplate,
} from './types';

export const initialOrganisation: Organisation = {
  id: 'org-1',
  name: 'Apex Global Solutions',
  address: '100 Montgomery St, Suite 1800, San Francisco, CA 94104',
  industry: 'Enterprise Technology & Services',
  logoUrl: '',
  website: 'https://apexsolutions.example.com',
  defaultCurrency: 'USD',
  timeZone: 'America/Los_Angeles',
  sharingPolicy: 'all_shared',
  teamWelcomeText: 'Welcome {userName} to the {teamName} Dashboard at {companyName}. Have an impactful, productive day!',
  allowTeamSharing: true,
  dataRetentionPolicyDays: 365,
  enforceAvailabilityChecking: true,
};

export const initialUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Jenkins',
    email: 'sarah.j@apexsolutions.com',
    role: 'admin',
    department: 'Executive Management',
    jobTitle: 'Chief Executive Officer',
    regionId: 'reg-1',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+1 (415) 555-0142',
    status: 'Available',
    statusMessage: 'In office · Reviewing Q3 executive priorities',
    location: 'San Francisco, CA (HQ)',
    bio: 'Founding CEO at Apex Global Solutions. 15+ years driving SaaS enterprise expansion, product vision, and strategic partnerships.',
    skills: ['Executive Leadership', 'Corporate Strategy', 'Enterprise Sales', 'Investor Relations'],
    joinedDate: '2022-01-10',
    lastActive: 'Just now',
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'America/Los_Angeles',
      welcomeText: 'Good day! Review your active deals and scheduled calls below.',
      clockMode: '12h',
      theme: 'light',
      activityDepth: 30,
      workingDayStart: '08:30',
      workingDayEnd: '17:30',
    },
    unavailableDates: ['2026-09-25'],
  },
  {
    id: 'user-2',
    name: 'David Ross',
    email: 'david.r@apexsolutions.com',
    role: 'manager',
    department: 'Sales & Revenue',
    jobTitle: 'VP of Sales',
    regionId: 'reg-1',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+1 (415) 555-0188',
    status: 'In a Meeting',
    statusMessage: 'Executive pipeline sync until 3:00 PM',
    location: 'San Francisco, CA (HQ)',
    bio: 'Leads global revenue strategy, commercial account executives, and sales engineering teams across North America.',
    skills: ['Sales Leadership', 'Pipeline Management', 'Contract Negotiation', 'Go-To-Market'],
    joinedDate: '2022-06-15',
    managerId: 'user-1',
    lastActive: '10m ago',
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'America/Los_Angeles',
      welcomeText: 'Ready for today? Track your sales pipeline and team targets.',
      clockMode: '12h',
      theme: 'light',
      activityDepth: 60,
      workingDayStart: '09:00',
      workingDayEnd: '18:00',
    },
    unavailableDates: [],
  },
  {
    id: 'user-3',
    name: 'Alex Rivera',
    email: 'alex.r@apexsolutions.com',
    role: 'standard',
    department: 'Sales & Revenue',
    jobTitle: 'Senior Account Executive',
    regionId: 'reg-2',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+1 (212) 555-0176',
    status: 'On Call',
    statusMessage: 'Client discovery call with CloudScale Networks',
    location: 'New York, NY',
    bio: 'Top-performing strategic account executive specializing in telecommunications and enterprise cloud infrastructure.',
    skills: ['Enterprise Prospecting', 'Solution Selling', 'Cloud Infrastructure', 'Deal Closing'],
    joinedDate: '2023-03-01',
    managerId: 'user-2',
    lastActive: '5m ago',
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'America/New_York',
      welcomeText: 'Focus on your priority call list and upcoming deal closings.',
      clockMode: '12h',
      theme: 'light',
      activityDepth: 30,
      workingDayStart: '09:00',
      workingDayEnd: '17:00',
    },
    unavailableDates: ['2026-09-21'],
  },
  {
    id: 'user-4',
    name: 'Elena Rostova',
    email: 'elena.r@apexsolutions.com',
    role: 'standard',
    department: 'Customer Success',
    jobTitle: 'Solutions Support Lead',
    regionId: 'reg-3',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+44 20 7946 0912',
    status: 'Available',
    statusMessage: 'Active on customer escalations & SLA triage',
    location: 'London, UK',
    bio: 'Experienced customer success and technical escalation lead focused on EMEA accounts, SLAs, and customer retention.',
    skills: ['Customer Success', 'Technical Support', 'Incident Management', 'SLA Adherence'],
    joinedDate: '2023-08-20',
    managerId: 'user-1',
    lastActive: 'Just now',
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'Europe/London',
      welcomeText: 'Support desk active: check open high-priority customer cases.',
      clockMode: '24h',
      theme: 'light',
      activityDepth: 45,
      workingDayStart: '08:00',
      workingDayEnd: '16:30',
    },
    unavailableDates: [],
  },
  {
    id: 'user-5',
    name: 'John Doe',
    email: 'john.doe@apexsolutions.com',
    role: 'manager',
    department: 'Sales & Revenue',
    jobTitle: 'Sales Team Manager',
    regionId: 'reg-1',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+1 (415) 555-0133',
    status: 'Available',
    statusMessage: 'Mentoring sales reps & coaching demos',
    location: 'San Francisco, CA (HQ)',
    bio: 'Directs account executive teams and handles mid-market accounts. Passionate about CRM adoption and outbound pipelines.',
    skills: ['Sales Coaching', 'Deal Closing', 'CRM Optimization', 'Account Management'],
    joinedDate: '2023-11-12',
    managerId: 'user-2',
    lastActive: '15m ago',
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'America/Los_Angeles',
      welcomeText: 'Drive pipeline acceleration and team coaching.',
      clockMode: '12h',
      theme: 'light',
      activityDepth: 30,
      workingDayStart: '09:00',
      workingDayEnd: '17:00',
    },
    unavailableDates: [],
  },
  {
    id: 'user-6',
    name: 'Sarah Ali',
    email: 'sarah.ali@apexsolutions.com',
    role: 'standard',
    department: 'Sales & Revenue',
    jobTitle: 'Commercial Account Executive',
    regionId: 'reg-1',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+1 (415) 555-0164',
    status: 'Away',
    statusMessage: 'Client lunch meeting · Back at 2:00 PM',
    location: 'San Francisco, CA (HQ)',
    bio: 'Drives commercial and mid-market growth across fintech and retail sectors. Expert in demo conversions and outbound sales.',
    skills: ['Inbound Sales', 'Outbound Prospecting', 'Product Demos', 'Customer Relationship'],
    joinedDate: '2024-02-01',
    managerId: 'user-5',
    lastActive: '45m ago',
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'America/Los_Angeles',
      welcomeText: 'Target high-growth enterprise prospects.',
      clockMode: '12h',
      theme: 'light',
      activityDepth: 30,
      workingDayStart: '09:00',
      workingDayEnd: '17:00',
    },
    unavailableDates: [],
  },
  {
    id: 'user-7',
    name: 'Rahul Das',
    email: 'rahul.das@apexsolutions.com',
    role: 'standard',
    department: 'Engineering',
    jobTitle: 'Principal Solutions Architect',
    regionId: 'reg-2',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+91 80 4123 4567',
    status: 'Busy',
    statusMessage: 'Deep work: finalizing security & cloud architecture',
    location: 'Bangalore, India',
    bio: 'Lead technical architect collaborating with enterprise sales for multi-cloud deployments, SOC2 compliance, and API integrations.',
    skills: ['Cloud Architecture', 'Security Compliance', 'API Integration', 'Technical Pre-Sales'],
    joinedDate: '2023-05-15',
    managerId: 'user-1',
    lastActive: '2m ago',
    preferences: {
      defaultCurrency: 'USD',
      timeZone: 'Asia/Kolkata',
      welcomeText: 'Architecture reviews and technical demonstrations.',
      clockMode: '12h',
      theme: 'light',
      activityDepth: 30,
      workingDayStart: '09:00',
      workingDayEnd: '17:00',
    },
    unavailableDates: [],
  },
];

export const initialRegions: Region[] = [
  {
    id: 'reg-1',
    name: 'North America West',
    code: 'NA-W',
    description: 'HQ and Pacific Time Zone clients',
    unavailableDates: ['2026-11-26', '2026-12-25'],
  },
  {
    id: 'reg-2',
    name: 'North America East',
    code: 'NA-E',
    description: 'Eastern seaboard commercial accounts',
    unavailableDates: ['2026-11-26', '2026-12-25'],
  },
  {
    id: 'reg-3',
    name: 'EMEA Hub (London)',
    code: 'EMEA',
    description: 'European and UK enterprise accounts',
    unavailableDates: ['2026-12-25', '2026-12-26'],
  },
];

export const initialExtendedFields: ExtendedField[] = [
  {
    id: 'ef-1',
    entity: 'company',
    label: 'Tax ID / VAT',
    key: 'vat_id',
    type: 'text',
    required: false,
  },
  {
    id: 'ef-2',
    entity: 'contact',
    label: 'LinkedIn Profile',
    key: 'linkedin_url',
    type: 'text',
    required: false,
  },
  {
    id: 'ef-3',
    entity: 'company',
    label: 'Account Tier',
    key: 'account_tier',
    type: 'select',
    options: ['Enterprise Plus', 'Growth Tier', 'Strategic Partner', 'Standard'],
    required: true,
  },
  {
    id: 'ef-4',
    entity: 'event',
    label: 'Meeting Conference Link',
    key: 'conference_link',
    type: 'text',
    required: false,
  },
];

export const initialFieldSets: FieldSets = {
  products: [
    'Cloud Data Platform Pro',
    'AI Workflow Suite',
    'Telematics Fleet Hub',
    'Enterprise Security Gateway',
    'Support & SLA Tier 1',
  ],
  dealStages: [
    { id: 'lead', name: 'Lead Qualified', probability: 20, color: '#64748b' },
    { id: 'discovery', name: 'Discovery & Needs', probability: 40, color: '#3b82f6' },
    { id: 'proposal', name: 'Proposal Sent', probability: 60, color: '#f59e0b' },
    { id: 'negotiation', name: 'Negotiation', probability: 80, color: '#8b5cf6' },
    { id: 'won', name: 'Closed Won', probability: 100, color: '#10b981' },
    { id: 'lost', name: 'Closed Lost', probability: 0, color: '#ef4444' },
  ],
  caseStatuses: ['New', 'Assigned', 'In Progress', 'Pending Customer', 'Resolved', 'Closed'],
  callOutcomes: [
    'Connected - Scheduled Demo',
    'Connected - Needs Follow-up',
    'Connected - Not Interested',
    'Left Voicemail',
    'Busy / No Answer',
    'Wrong Number',
  ],
  priorityLevels: ['Low', 'Medium', 'High', 'Critical'],
  industries: [
    'Enterprise Technology',
    'Healthcare & Life Sciences',
    'Logistics & Supply Chain',
    'Financial Services',
    'Manufacturing & Robotics',
    'Retail & E-commerce',
  ],
};

export const initialCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'CloudScale Networks',
    industry: 'Enterprise Technology',
    annualRevenue: 18500000,
    employeeCount: 210,
    phone: '+1 (415) 890-2345',
    website: 'https://cloudscalenetworks.example.com',
    billingAddress: '450 Mission St, San Francisco, CA 94105',
    shippingAddress: '450 Mission St, San Francisco, CA 94105',
    priority: 'High',
    ownerId: 'user-3',
    regionId: 'reg-1',
    description: 'High-growth multi-cloud infrastructure software provider expanding rapidly across US West.',
    isDefault: true,
    customFields: { vat_id: 'US-94-1827461', account_tier: 'Enterprise Plus' },
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-15T14:30:00Z',
  },
  {
    id: 'comp-2',
    name: 'BioVance Health Labs',
    industry: 'Healthcare & Life Sciences',
    annualRevenue: 34000000,
    employeeCount: 430,
    phone: '+1 (617) 555-8791',
    website: 'https://biovancehealth.example.com',
    billingAddress: '100 Binney St, Cambridge, MA 02142',
    shippingAddress: '100 Binney St, Cambridge, MA 02142',
    priority: 'Critical',
    ownerId: 'user-3',
    regionId: 'reg-2',
    description: 'Genomics and diagnostic data pipelines provider. Looking for secure compliant platform.',
    isDefault: false,
    customFields: { vat_id: 'US-04-9812734', account_tier: 'Enterprise Plus' },
    createdAt: '2026-08-14T11:00:00Z',
    updatedAt: '2026-09-14T09:20:00Z',
  },
  {
    id: 'comp-3',
    name: 'Nexus Logistics Group',
    industry: 'Logistics & Supply Chain',
    annualRevenue: 9800000,
    employeeCount: 120,
    phone: '+1 (312) 640-1920',
    website: 'https://nexuslogistics.example.com',
    billingAddress: '233 S Wacker Dr, Chicago, IL 60606',
    shippingAddress: '233 S Wacker Dr, Chicago, IL 60606',
    priority: 'Medium',
    ownerId: 'user-2',
    regionId: 'reg-1',
    description: 'Freight broker with automated dispatch network. Seeking fleet routing analytics.',
    isDefault: false,
    customFields: { vat_id: 'US-36-8172635', account_tier: 'Growth Tier' },
    createdAt: '2026-08-18T16:00:00Z',
    updatedAt: '2026-09-12T11:45:00Z',
  },
  {
    id: 'comp-4',
    name: 'FinEdge Wealth Advisory',
    industry: 'Financial Services',
    annualRevenue: 27000000,
    employeeCount: 180,
    phone: '+1 (212) 430-9988',
    website: 'https://finedgewealth.example.com',
    billingAddress: '388 Greenwich St, New York, NY 10013',
    shippingAddress: '388 Greenwich St, New York, NY 10013',
    priority: 'High',
    ownerId: 'user-3',
    regionId: 'reg-2',
    description: 'Institutional asset manager and advisory firm seeking enterprise-grade security gateway.',
    isDefault: false,
    customFields: { vat_id: 'US-13-4491029', account_tier: 'Strategic Partner' },
    createdAt: '2026-08-25T14:15:00Z',
    updatedAt: '2026-09-16T15:00:00Z',
  },
  {
    id: 'comp-5',
    name: 'Quantum Robotics Inc',
    industry: 'Manufacturing & Robotics',
    annualRevenue: 6200000,
    employeeCount: 65,
    phone: '+44 20 7946 0912',
    website: 'https://quantumrobotics.example.com',
    billingAddress: '25 Bank St, Canary Wharf, London E14 5JP',
    shippingAddress: '25 Bank St, Canary Wharf, London E14 5JP',
    priority: 'Medium',
    ownerId: 'user-4',
    regionId: 'reg-3',
    description: 'Precision robotic assembly units for cleanroom fabrication in Western Europe.',
    isDefault: false,
    customFields: { vat_id: 'GB-992-1082-34', account_tier: 'Standard' },
    createdAt: '2026-09-01T08:30:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'comp-abc',
    name: 'ABC Ltd',
    industry: 'Enterprise Software & IT',
    annualRevenue: 12500000,
    employeeCount: 180,
    phone: '+91 98765 43210',
    website: 'https://abcltd.example.com',
    billingAddress: 'Tower 4, Cyber City, Bangalore, India',
    shippingAddress: 'Tower 4, Cyber City, Bangalore, India',
    priority: 'High',
    ownerId: 'user-7', // Rahul Das
    regionId: 'reg-3',
    description: 'Technology solutions company with expansion in APAC and EMEA markets.',
    isDefault: false,
    createdAt: '2026-08-20T08:30:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'comp-xyz',
    name: 'XYZ Ltd',
    industry: 'Financial Technologies',
    annualRevenue: 28000000,
    employeeCount: 320,
    phone: '+1 (212) 555-0199',
    website: 'https://xyzltd.example.com',
    billingAddress: '75 Wall St, New York, NY 10005',
    shippingAddress: '75 Wall St, New York, NY 10005',
    priority: 'Critical',
    ownerId: 'user-5', // John Doe
    regionId: 'reg-2',
    description: 'High frequency clearing and settlement workflows provider.',
    isDefault: false,
    createdAt: '2026-08-22T09:00:00Z',
    updatedAt: '2026-09-15T10:00:00Z',
  },
];

export const initialContacts: Contact[] = [
  {
    id: 'con-john-client',
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe@abcltd.example.com',
    phone: '+91 98765 43210',
    mobile: '+91 98765 43211',
    jobTitle: 'Chief Procurement Officer',
    messagingHandle: '@john_abc',
    mailingAddress: 'Tower 4, Cyber City, Bangalore, India',
    shippingAddress: 'Tower 4, Cyber City, Bangalore, India',
    ownerId: 'user-7', // Rahul Das
    companyId: 'comp-abc',
    type: 'lead',
    description: 'Key stakeholder reviewing RFP for CRM modernization and workflow automation.',
    createdAt: '2026-08-20T09:15:00Z',
    updatedAt: '2026-09-15T15:00:00Z',
  },
  {
    id: 'con-sarah-client',
    firstName: 'Sarah',
    lastName: 'Ali',
    email: 'sarah.ali@xyzltd.example.com',
    phone: '+1 (212) 555-0199',
    mobile: '+1 (212) 555-0188',
    jobTitle: 'VP of Commercial Strategy',
    messagingHandle: '@sarah_xyz',
    mailingAddress: '75 Wall St, New York, NY 10005',
    shippingAddress: '75 Wall St, New York, NY 10005',
    ownerId: 'user-5', // John Doe
    companyId: 'comp-xyz',
    type: 'customer',
    description: 'Direct sponsor for multi-region financial reporting integration.',
    createdAt: '2026-08-22T10:00:00Z',
    updatedAt: '2026-09-16T11:00:00Z',
  },
  {
    id: 'con-1',
    firstName: 'Marcus',
    lastName: 'Vance',
    email: 'm.vance@cloudscalenetworks.example.com',
    phone: '+1 (415) 890-2346',
    mobile: '+1 (415) 912-8811',
    jobTitle: 'VP of Technology & Infrastructure',
    messagingHandle: '@marcus_vance',
    mailingAddress: '450 Mission St, San Francisco, CA 94105',
    shippingAddress: '450 Mission St, San Francisco, CA 94105',
    ownerId: 'user-3',
    companyId: 'comp-1',
    type: 'customer',
    description: 'Primary decision maker for cloud data platform modernization. Preferred contact time: mornings.',
    campaignIds: ['camp-1'],
    customFields: { linkedin_url: 'https://linkedin.com/in/marcusvance-tech' },
    createdAt: '2026-08-11T09:15:00Z',
    updatedAt: '2026-09-15T15:00:00Z',
  },
  {
    id: 'con-2',
    firstName: 'Dr. Evelyn',
    lastName: 'Reed',
    email: 'ereed@biovancehealth.example.com',
    phone: '+1 (617) 555-8792',
    mobile: '+1 (617) 320-4491',
    jobTitle: 'Chief Medical Informatics Officer',
    messagingHandle: '@drevelynreed',
    mailingAddress: '100 Binney St, Cambridge, MA 02142',
    shippingAddress: '100 Binney St, Cambridge, MA 02142',
    ownerId: 'user-3',
    companyId: 'comp-2',
    type: 'lead',
    description: 'Interested in HIPAA-compliant diagnostic platform licensing. Needs legal data protection addendum.',
    campaignIds: ['camp-1'],
    customFields: { linkedin_url: 'https://linkedin.com/in/evelynreed-md' },
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-16T11:00:00Z',
  },
  {
    id: 'con-3',
    firstName: 'Carlos',
    lastName: 'Mendoza',
    email: 'cmendoza@nexuslogistics.example.com',
    phone: '+1 (312) 640-1921',
    mobile: '+1 (312) 710-8233',
    jobTitle: 'Director of Global Fleet Operations',
    messagingHandle: '@carlos_nexus',
    mailingAddress: '233 S Wacker Dr, Chicago, IL 60606',
    shippingAddress: '233 S Wacker Dr, Chicago, IL 60606',
    ownerId: 'user-2',
    companyId: 'comp-3',
    type: 'customer',
    description: 'Managed implementation of initial fleet telematics. Happy reference customer.',
    campaignIds: [],
    customFields: { linkedin_url: 'https://linkedin.com/in/carlosmendoza-ops' },
    createdAt: '2026-08-19T14:30:00Z',
    updatedAt: '2026-09-12T16:00:00Z',
  },
  {
    id: 'con-4',
    firstName: 'Rachel',
    lastName: 'Sterling',
    email: 'rsterling@finedgewealth.example.com',
    phone: '+1 (212) 430-9989',
    mobile: '+1 (917) 443-1288',
    jobTitle: 'Chief Information Security Officer',
    messagingHandle: '@rachel_sterling_sec',
    mailingAddress: '388 Greenwich St, New York, NY 10013',
    shippingAddress: '388 Greenwich St, New York, NY 10013',
    ownerId: 'user-3',
    companyId: 'comp-4',
    type: 'lead',
    description: 'Evaluating Enterprise Security Gateway for SEC/FINRA compliance standards.',
    campaignIds: ['camp-1'],
    customFields: { linkedin_url: 'https://linkedin.com/in/rachelsterling-ciso' },
    createdAt: '2026-08-26T11:30:00Z',
    updatedAt: '2026-09-16T14:10:00Z',
  },
  {
    id: 'con-5',
    firstName: 'James',
    lastName: 'Tanaka',
    email: 'j.tanaka@quantumrobotics.example.com',
    phone: '+44 20 7946 0914',
    mobile: '+44 7700 900341',
    jobTitle: 'Lead Robotics Software Architect',
    messagingHandle: '@jtanaka_robotics',
    mailingAddress: '25 Bank St, Canary Wharf, London E14 5JP',
    shippingAddress: '25 Bank St, Canary Wharf, London E14 5JP',
    ownerId: 'user-4',
    companyId: 'comp-5',
    type: 'lead',
    description: 'Requested technical documentation on AI Workflow Suite API integration.',
    campaignIds: [],
    customFields: { linkedin_url: 'https://linkedin.com/in/jamestanaka-robotics' },
    createdAt: '2026-09-02T13:45:00Z',
    updatedAt: '2026-09-14T10:00:00Z',
  },
  {
    id: 'con-6',
    firstName: 'Sophia',
    lastName: 'Lorenzi',
    email: 'sophia@lorenzi-procurement.example.com',
    phone: '+1 (206) 555-0149',
    mobile: '+1 (206) 555-0199',
    jobTitle: 'Strategic Procurement Advisor',
    messagingHandle: '@slorenzi',
    mailingAddress: '1201 3rd Ave, Seattle, WA 98101',
    shippingAddress: '1201 3rd Ave, Seattle, WA 98101',
    ownerId: 'user-1',
    type: 'vendor',
    description: 'Independent advisor facilitating vendor selection for Pacific Northwest enterprises.',
    campaignIds: [],
    customFields: { linkedin_url: 'https://linkedin.com/in/sophialorenzi' },
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-05T09:00:00Z',
  },
];

export const initialDeals: Deal[] = [
  {
    id: 'deal-1',
    title: 'CloudScale Enterprise Cloud Data Platform',
    companyId: 'comp-1',
    contactId: 'con-1',
    product: 'Cloud Data Platform Pro',
    value: 120000,
    currency: 'USD',
    stage: 'proposal',
    status: 'open',
    expectedCloseDate: '2026-10-15',
    nextStep: 'Present finalized security and architecture blueprint with executive sponsor',
    ownerId: 'user-3',
    description: 'Multi-year deployment for 180 engineers with automated schema migrations and HA failover.',
    targetId: 'tar-1',
    history: [
      { timestamp: '2026-08-12T10:00:00Z', actor: 'Alex Rivera', action: 'Created deal in Lead Qualified' },
      { timestamp: '2026-08-28T14:30:00Z', actor: 'Alex Rivera', action: 'Moved to Discovery & Needs', fromStage: 'lead', toStage: 'discovery' },
      { timestamp: '2026-09-10T16:00:00Z', actor: 'Alex Rivera', action: 'Moved to Proposal Sent', fromStage: 'discovery', toStage: 'proposal', note: 'Sent v2 proposal quoting $120k ARR' },
    ],
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-09-10T16:00:00Z',
  },
  {
    id: 'deal-2',
    title: 'BioVance Diagnostic Platform AI Licensing',
    companyId: 'comp-2',
    contactId: 'con-2',
    product: 'AI Workflow Suite',
    value: 245000,
    currency: 'USD',
    stage: 'negotiation',
    status: 'open',
    expectedCloseDate: '2026-09-30',
    nextStep: 'Complete legal review of Business Associate Agreement (BAA)',
    ownerId: 'user-3',
    description: 'High-margin AI diagnostic engine deployment. In final terms discussion.',
    targetId: 'tar-1',
    history: [
      { timestamp: '2026-08-16T11:00:00Z', actor: 'Alex Rivera', action: 'Created deal' },
      { timestamp: '2026-09-02T15:00:00Z', actor: 'Alex Rivera', action: 'Moved to Proposal Sent', fromStage: 'discovery', toStage: 'proposal' },
      { timestamp: '2026-09-14T10:15:00Z', actor: 'Alex Rivera', action: 'Moved to Negotiation', fromStage: 'proposal', toStage: 'negotiation', note: 'Discount locked at 8% with 3-year term' },
    ],
    createdAt: '2026-08-16T11:00:00Z',
    updatedAt: '2026-09-14T10:15:00Z',
  },
  {
    id: 'deal-3',
    title: 'Nexus Fleet Telematics Integration',
    companyId: 'comp-3',
    contactId: 'con-3',
    product: 'Telematics Fleet Hub',
    value: 58000,
    currency: 'USD',
    stage: 'won',
    status: 'won',
    expectedCloseDate: '2026-09-10',
    nextStep: 'Onboarding kickoff completed. Handed off to Customer Success.',
    ownerId: 'user-2',
    description: 'Connected 120 long-haul trucks with live GPS telematics and driver safety alerts.',
    targetId: 'tar-1',
    history: [
      { timestamp: '2026-08-20T09:00:00Z', actor: 'David Ross', action: 'Created deal' },
      { timestamp: '2026-09-01T11:00:00Z', actor: 'David Ross', action: 'Moved to Negotiation' },
      { timestamp: '2026-09-10T17:00:00Z', actor: 'David Ross', action: 'Closed Won deal', fromStage: 'negotiation', toStage: 'won', note: 'Contracts signed via DocuSign' },
    ],
    createdAt: '2026-08-20T09:00:00Z',
    updatedAt: '2026-09-10T17:00:00Z',
  },
  {
    id: 'deal-4',
    title: 'FinEdge Security Gateway Implementation',
    companyId: 'comp-4',
    contactId: 'con-4',
    product: 'Enterprise Security Gateway',
    value: 85000,
    currency: 'USD',
    stage: 'discovery',
    status: 'open',
    expectedCloseDate: '2026-11-20',
    nextStep: 'Schedule technical deep dive on SOC2 Type II and pen-test results',
    ownerId: 'user-3',
    description: 'Evaluation of zero-trust gateway for wealth advisors accessing portfolio databases.',
    targetId: 'tar-1',
    history: [
      { timestamp: '2026-08-27T10:00:00Z', actor: 'Alex Rivera', action: 'Created deal' },
      { timestamp: '2026-09-05T14:00:00Z', actor: 'Alex Rivera', action: 'Moved to Discovery', fromStage: 'lead', toStage: 'discovery' },
    ],
    createdAt: '2026-08-27T10:00:00Z',
    updatedAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'deal-5',
    title: 'Quantum Robotics Vision Workflow Suite',
    companyId: 'comp-5',
    contactId: 'con-5',
    product: 'AI Workflow Suite',
    value: 45000,
    currency: 'USD',
    stage: 'lead',
    status: 'open',
    expectedCloseDate: '2026-12-05',
    nextStep: 'Follow up on technical feasibility whitepaper download',
    ownerId: 'user-4',
    description: 'Robotic arm optical defect inspection pipeline.',
    history: [
      { timestamp: '2026-09-04T12:00:00Z', actor: 'Elena Rostova', action: 'Created deal from inbound website inquiry' },
    ],
    createdAt: '2026-09-04T12:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Send revised BAA contract terms to BioVance legal team',
    deadline: '2026-09-18',
    status: 'In Progress',
    completionPercentage: 70,
    assigneeId: 'user-3',
    companyId: 'comp-2',
    contactId: 'con-2',
    description: 'Coordinate with internal legal on Section 4 indemnification clause before dispatching.',
    history: [
      { timestamp: '2026-09-15T09:00:00Z', actor: 'Alex Rivera', oldPercent: 0, newPercent: 40, oldStatus: 'Not Started', newStatus: 'In Progress', note: 'Draft received from legal' },
      { timestamp: '2026-09-16T15:00:00Z', actor: 'Alex Rivera', oldPercent: 40, newPercent: 70, oldStatus: 'In Progress', newStatus: 'In Progress', note: 'Incorporated Dr. Reed comments' },
    ],
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-16T15:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Prepare executive architecture slide deck for CloudScale demo',
    deadline: '2026-09-19',
    status: 'In Progress',
    completionPercentage: 50,
    assigneeId: 'user-3',
    companyId: 'comp-1',
    contactId: 'con-1',
    description: 'Outline hybrid cloud sync topologies and backup failover benchmarks.',
    history: [
      { timestamp: '2026-09-16T10:00:00Z', actor: 'Alex Rivera', oldPercent: 0, newPercent: 50, oldStatus: 'Not Started', newStatus: 'In Progress' },
    ],
    createdAt: '2026-09-16T10:00:00Z',
    updatedAt: '2026-09-16T10:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Execute Q3 sales target performance review with regional team',
    deadline: '2026-09-22',
    status: 'Not Started',
    completionPercentage: 0,
    assigneeId: 'user-2',
    description: 'Review attainment against $450k team quarterly revenue goal.',
    history: [],
    createdAt: '2026-09-14T08:00:00Z',
    updatedAt: '2026-09-14T08:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Resolve high priority API rate limiting ticket for CloudScale',
    deadline: '2026-09-17',
    status: 'In Progress',
    completionPercentage: 80,
    assigneeId: 'user-4',
    companyId: 'comp-1',
    description: 'Increase production cluster egress burst limits to 5,000 req/min.',
    history: [],
    createdAt: '2026-09-17T08:00:00Z',
    updatedAt: '2026-09-17T09:30:00Z',
  },
  {
    id: 'task-5',
    title: 'Follow up with FinEdge compliance officer regarding audit logs',
    deadline: '2026-09-16', // overdue
    status: 'Not Started',
    completionPercentage: 0,
    assigneeId: 'user-3',
    companyId: 'comp-4',
    contactId: 'con-4',
    description: 'Provide cryptographic checksum specification for archive export verification.',
    history: [],
    createdAt: '2026-09-13T11:00:00Z',
    updatedAt: '2026-09-13T11:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Review Board Deck for Q4 strategic cloud expansion',
    deadline: '2026-09-28',
    status: 'In Progress',
    completionPercentage: 85,
    assigneeId: 'user-1',
    description: 'Finalize ARR guidance and APAC partnership announcements.',
    history: [],
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-25T14:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Lead weekly sales coaching on objection handling',
    deadline: '2026-09-29',
    status: 'Completed',
    completionPercentage: 100,
    assigneeId: 'user-5',
    description: 'Review competitive battlecards and enterprise pricing concessions.',
    history: [],
    createdAt: '2026-09-22T09:00:00Z',
    updatedAt: '2026-09-27T16:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Deliver follow-up commercial proposal to XYZ Ltd',
    deadline: '2026-09-30',
    status: 'In Progress',
    completionPercentage: 60,
    assigneeId: 'user-6',
    companyId: 'comp-xyz',
    contactId: 'con-sarah-client',
    description: 'Incorporate tiered user seat volume discounts requested by Sarah Ali.',
    history: [],
    createdAt: '2026-09-24T11:30:00Z',
    updatedAt: '2026-09-27T10:00:00Z',
  },
  {
    id: 'task-9',
    title: 'Finalize enterprise architecture specification for ABC Ltd',
    deadline: '2026-10-02',
    status: 'In Progress',
    completionPercentage: 45,
    assigneeId: 'user-7',
    companyId: 'comp-abc',
    contactId: 'con-john-client',
    description: 'Document VPC peering, identity federation, and latency failover.',
    history: [],
    createdAt: '2026-09-25T08:00:00Z',
    updatedAt: '2026-09-27T12:00:00Z',
  },
];

export const initialCases: Case[] = [
  {
    id: 'case-1',
    title: 'Inbound Webhook latency degradation during peak traffic',
    problemName: 'Slow webhook response (>1.8s) causing client timeouts',
    status: 'In Progress',
    priority: 'Critical',
    ownerId: 'user-4',
    companyId: 'comp-1',
    contactId: 'con-1',
    description: 'CloudScale ingest pipeline reported dropped webhook packets between 14:00 - 15:30 UTC yesterday.',
    teamMemberIds: ['user-4', 'user-1'],
    internalNotes: [
      { id: 'cn-1', author: 'Elena Rostova', text: 'Identified connection pool exhaustion on replica DB. Patching worker pool size.', createdAt: '2026-09-16T16:00:00Z' },
      { id: 'cn-2', author: 'Sarah Jenkins', text: 'Confirmed load balancer retry policy tuned. Monitoring live latency.', createdAt: '2026-09-17T07:15:00Z' },
    ],
    createdAt: '2026-09-16T15:40:00Z',
    updatedAt: '2026-09-17T07:15:00Z',
  },
  {
    id: 'case-2',
    title: 'Telematics GPS heartbeat discrepancy on fleet unit #42',
    problemName: 'Cellular modem packet loss in mountainous route',
    status: 'Resolved',
    priority: 'Medium',
    ownerId: 'user-4',
    companyId: 'comp-3',
    contactId: 'con-3',
    description: 'Nexus vehicle 42 lost tracking ping for 45 minutes on I-70 corridor.',
    closedDate: '2026-09-15',
    teamMemberIds: ['user-4'],
    internalNotes: [
      { id: 'cn-3', author: 'Elena Rostova', text: 'Firmware updated to store-and-forward offline buffer mode. Verified sync on reconnection.', createdAt: '2026-09-15T14:00:00Z' },
    ],
    createdAt: '2026-09-14T11:00:00Z',
    updatedAt: '2026-09-15T14:30:00Z',
  },
  {
    id: 'case-3',
    title: 'Custom export delimiter rendering issue in legacy spreadsheet',
    problemName: 'Tab delimited exports enclosed quotes unexpectedly',
    status: 'New',
    priority: 'Low',
    ownerId: 'user-4',
    companyId: 'comp-5',
    contactId: 'con-5',
    description: 'Client is using an older spreadsheet macro expecting unquoted tab separation.',
    teamMemberIds: ['user-4'],
    internalNotes: [],
    createdAt: '2026-09-17T06:30:00Z',
    updatedAt: '2026-09-17T06:30:00Z',
  },
];

const getDynamicDate = (offsetDays: number = 0): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const initialEvents: Event[] = [
  {
    id: 'evt-conflict-sarah',
    title: 'Client Meeting',
    startDate: getDynamicDate(0), // Today
    startTime: '10:00',
    endDate: getDynamicDate(0),
    endTime: '11:00',
    participantIds: ['user-6'], // Sarah Ali
    confirmed: true,
    location: 'Client HQ / Executive Conference',
    locationType: 'office',
    meetingLink: 'https://meet.google.com/xyz-client-mtg',
    agenda: 'Strategic enterprise client consultation and account roadmap.',
    notes: 'Q3 requirement gathering and contract review.',
    emailAlert: true,
    ownerId: 'user-6',
    isMeeting: true,
    meetingStatus: 'Scheduled',
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-20T08:00:00Z',
  },
  {
    id: 'evt-conflict-sarah-tmrw',
    title: 'Client Meeting',
    startDate: getDynamicDate(1), // Tomorrow
    startTime: '10:00',
    endDate: getDynamicDate(1),
    endTime: '11:00',
    participantIds: ['user-6'], // Sarah Ali
    confirmed: true,
    location: 'Client HQ / Executive Conference',
    locationType: 'office',
    meetingLink: 'https://meet.google.com/xyz-client-mtg',
    agenda: 'Strategic enterprise client consultation and account roadmap.',
    notes: 'Q3 requirement gathering and contract review.',
    emailAlert: true,
    ownerId: 'user-6',
    isMeeting: true,
    meetingStatus: 'Scheduled',
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-20T08:00:00Z',
  },
  {
    id: 'evt-conflict-sarah-static-28',
    title: 'Client Meeting',
    startDate: '2026-09-28',
    startTime: '10:00',
    endDate: '2026-09-28',
    endTime: '11:00',
    participantIds: ['user-6'], // Sarah Ali
    confirmed: true,
    location: 'Client HQ / Executive Conference',
    locationType: 'office',
    meetingLink: 'https://meet.google.com/xyz-client-mtg',
    agenda: 'Strategic enterprise client consultation and account roadmap.',
    notes: 'Q3 requirement gathering and contract review.',
    emailAlert: true,
    ownerId: 'user-6',
    isMeeting: true,
    meetingStatus: 'Scheduled',
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-20T08:00:00Z',
  },
  {
    id: 'evt-conflict-sarah-static-27',
    title: 'Client Meeting',
    startDate: '2026-09-27',
    startTime: '10:00',
    endDate: '2026-09-27',
    endTime: '11:00',
    participantIds: ['user-6'], // Sarah Ali
    confirmed: true,
    location: 'Client HQ / Executive Conference',
    locationType: 'office',
    meetingLink: 'https://meet.google.com/xyz-client-mtg',
    agenda: 'Strategic enterprise client consultation and account roadmap.',
    notes: 'Q3 requirement gathering and contract review.',
    emailAlert: true,
    ownerId: 'user-6',
    isMeeting: true,
    meetingStatus: 'Scheduled',
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-20T08:00:00Z',
  },
  {
    id: 'evt-1',
    title: 'CloudScale Architecture Review & Security Briefing',
    startDate: getDynamicDate(-1),
    startTime: '10:00',
    endDate: getDynamicDate(-1),
    endTime: '11:00',
    participantIds: ['user-3', 'user-1', 'user-7'],
    confirmed: true,
    companyId: 'comp-1',
    contactId: 'con-1',
    dealId: 'deal-1',
    location: 'Video Conference / Room 4B',
    locationType: 'online',
    meetingLink: 'https://meet.google.com/cscale-arch-rev',
    notes: 'Cover data retention, multi-tenant isolation, and automated failover guarantees.',
    agenda: '1. Review current multi-cloud topology\n2. Discuss failover latency SLAs\n3. Finalize data retention requirements',
    emailAlert: true,
    ownerId: 'user-3',
    isMeeting: true,
    meetingStatus: 'Completed',
    meetingOutcome: 'Successful - Next Steps Defined',
    outcomeNotes: 'Client technical committee signed off on the architecture. Moving to BAA and pricing approval.',
    createdAt: '2026-09-12T14:00:00Z',
    updatedAt: '2026-09-12T14:00:00Z',
  },
  {
    id: 'evt-2',
    title: 'BioVance BAA Contract & Legal Terms Finalization',
    startDate: getDynamicDate(2),
    startTime: '14:00',
    endDate: getDynamicDate(2),
    endTime: '15:00',
    participantIds: ['user-3', 'user-2', 'user-5'],
    confirmed: true,
    companyId: 'comp-2',
    contactId: 'con-2',
    dealId: 'deal-2',
    location: 'Executive Zoom Boardroom',
    locationType: 'online',
    meetingLink: 'https://zoom.us/j/9823471923',
    directions: 'Meeting passcode sent via secure channel',
    notes: 'Walk through Section 4 indemnity with Dr. Reed and general counsel.',
    agenda: 'Review revised BAA redlines and clarify IP rights for generated AI outputs.',
    emailAlert: true,
    ownerId: 'user-3',
    isMeeting: true,
    meetingStatus: 'Scheduled',
    reminderMinutes: 30,
    createdAt: '2026-09-14T16:00:00Z',
    updatedAt: '2026-09-14T16:00:00Z',
  },
  {
    id: 'evt-3',
    title: 'Weekly Sales Pipeline & Target Review',
    startDate: getDynamicDate(3),
    startTime: '09:00',
    endDate: getDynamicDate(3),
    endTime: '10:00',
    participantIds: ['user-1', 'user-2', 'user-3', 'user-4', 'user-5', 'user-6', 'user-7'],
    confirmed: true,
    location: 'Main Conference Hall & Remote Sync',
    locationType: 'custom',
    meetingLink: 'https://meet.google.com/apex-all-sales',
    notes: 'Review month-to-date deals won, stalled negotiations, and outreach campaigns.',
    agenda: '1. Attainment vs $450k goal\n2. Blockers in enterprise procurement\n3. High-intent inbound leads review',
    emailAlert: true,
    ownerId: 'user-2',
    isMeeting: true,
    meetingStatus: 'Scheduled',
    reminderMinutes: 15,
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-10T10:00:00Z',
  },
];

export const initialCallScripts: CallScript[] = [
  {
    id: 'script-1',
    name: 'Enterprise Discovery & Qualification Script',
    description: 'Standard 4-question script used by sales reps during initial qualification calls.',
    elements: [
      {
        id: 'el-1',
        type: 'instruction',
        prompt: 'Warmly introduce yourself and confirm if now is still a convenient time for a 10-minute discovery call.',
      },
      {
        id: 'el-2',
        type: 'yes_no',
        prompt: 'Is the organization actively budgeting for a cloud data modernization project this calendar year?',
      },
      {
        id: 'el-3',
        type: 'multiple_choice',
        prompt: 'What is their primary architectural driver?',
        options: ['Security & Compliance (SOC2/HIPAA)', 'Scale & Multi-region latency', 'Cost optimization', 'Developer ergonomics'],
      },
      {
        id: 'el-4',
        type: 'free_text',
        prompt: 'Key requirements and agreed next action items:',
      },
    ],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'script-2',
    name: 'Support Ticket Escalation Check',
    description: 'Support rep checklist for verifying customer urgency and reproducing system incidents.',
    elements: [
      {
        id: 'el-21',
        type: 'instruction',
        prompt: 'Express empathy for the interruption and assure client of our tier-1 priority support handling.',
      },
      {
        id: 'el-22',
        type: 'yes_no',
        prompt: 'Is production data traffic currently being impacted or degraded?',
      },
      {
        id: 'el-23',
        type: 'multiple_choice',
        prompt: 'Severity Level Classification:',
        options: ['P1 - Outage (All users blocked)', 'P2 - Degraded Performance', 'P3 - Minor bug / workaround available', 'P4 - General inquiry'],
      },
      {
        id: 'el-24',
        type: 'free_text',
        prompt: 'Steps taken to reproduce and customer engineer contact on standby:',
      },
    ],
    createdAt: '2026-08-05T00:00:00Z',
  },
];

export const initialCalls: Call[] = [
  {
    id: 'call-1',
    subject: 'Follow up on Enterprise Automation RFP proposal',
    callPurpose: 'Review commercial terms, volume pricing discounts, and timeline',
    priority: 'High',
    status: 'Pending',
    dueDate: '2026-09-28',
    date: '2026-09-28',
    time: '11:00',
    durationMinutes: 30,
    direction: 'outbound',
    outcomeStatus: 'Pending',
    companyId: 'comp-abc',
    contactId: 'con-john-client',
    assignedUserId: 'user-7', // Rahul Das
    notes: 'John requested final numbers on the multi-region license bundle before board approval.',
    scriptId: 'script-1',
    isScheduled: false,
    isCompleted: false,
    createdAt: '2026-09-27T14:00:00Z',
    updatedAt: '2026-09-27T14:00:00Z',
  },
  {
    id: 'call-2',
    subject: 'Q4 Contract Execution & Governance Review',
    callPurpose: 'Executive alignment on Q4 rollout schedule and compliance sign-off',
    priority: 'High',
    status: 'Scheduled',
    date: '2026-09-28',
    time: '16:00',
    durationMinutes: 30,
    direction: 'outbound',
    outcomeStatus: 'Scheduled',
    companyId: 'comp-xyz',
    contactId: 'con-sarah-client',
    assignedUserId: 'user-5', // John Doe
    notes: 'Pre-arranged call with Sarah Ali. Review indemnification and data sovereignty terms.',
    scriptId: 'script-1',
    scheduledCalendarEventId: 'evt-call-sarah',
    isScheduled: true,
    isCompleted: false,
    createdAt: '2026-09-25T10:00:00Z',
    updatedAt: '2026-09-25T10:00:00Z',
  },
  {
    id: 'call-3',
    subject: 'URGENT: FinEdge Security Audit & SOC2 Addendum',
    callPurpose: 'Address security questionnaire blockers for Q4 closing',
    priority: 'High',
    status: 'Overdue',
    dueDate: '2026-09-26',
    date: '2026-09-26',
    time: '10:00',
    durationMinutes: 30,
    direction: 'outbound',
    outcomeStatus: 'Overdue',
    companyId: 'comp-4',
    contactId: 'con-4',
    assignedUserId: 'user-3', // Alex Rivera
    notes: 'Rachel needed urgent clarification on encryption keys rotation and customer-managed HSM.',
    scriptId: 'script-2',
    isScheduled: false,
    isCompleted: false,
    createdAt: '2026-09-25T07:30:00Z',
    updatedAt: '2026-09-26T18:00:00Z',
  },
  {
    id: 'call-4',
    subject: 'Nexus Logistics: Telematics Fleet Integration Checkpoint',
    callPurpose: 'Live verification of telemetry sensor API feeds with Carlos Mendoza',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: '2026-09-28',
    date: '2026-09-28',
    time: '12:00',
    durationMinutes: 45,
    direction: 'outbound',
    outcomeStatus: 'In Progress',
    companyId: 'comp-3',
    contactId: 'con-3',
    assignedUserId: 'user-2', // David Ross
    notes: 'Currently engaged with Carlos and his integration engineers on payload latency test.',
    isScheduled: false,
    isCompleted: false,
    createdAt: '2026-09-28T11:45:00Z',
    updatedAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'call-5',
    subject: 'Reconnect: BioVance Genomics Data Pipeline License',
    callPurpose: 'Discuss revised SLA tiers with Dr. Evelyn Reed',
    priority: 'High',
    status: 'No Answer',
    dueDate: '2026-09-28',
    date: '2026-09-28',
    time: '09:30',
    durationMinutes: 15,
    direction: 'outbound',
    outcomeStatus: 'No Answer',
    companyId: 'comp-2',
    contactId: 'con-2',
    assignedUserId: 'user-5', // John Doe
    notes: 'Called at 9:30 AM, reached voicemail. Left detailed callback message regarding HIPAA pricing.',
    scriptId: 'script-1',
    isScheduled: false,
    isCompleted: false,
    createdAt: '2026-09-28T09:00:00Z',
    updatedAt: '2026-09-28T09:35:00Z',
  },
  {
    id: 'call-6',
    subject: 'Overdue: CloudScale Multi-Tenant Single Sign-On Configuration',
    callPurpose: 'Resolve SAML 2.0 federation certificate mismatch',
    priority: 'Medium',
    status: 'Overdue',
    dueDate: '2026-09-27',
    date: '2026-09-27',
    time: '15:00',
    durationMinutes: 30,
    direction: 'outbound',
    outcomeStatus: 'Overdue',
    companyId: 'comp-1',
    contactId: 'con-1',
    assignedUserId: 'user-6', // Sarah Ali
    notes: 'Client administrator reported failure on Okta metadata import. Needs priority callback.',
    isScheduled: false,
    isCompleted: false,
    createdAt: '2026-09-26T14:00:00Z',
    updatedAt: '2026-09-27T17:00:00Z',
  },
  {
    id: 'call-7',
    subject: 'CloudScale Architecture RFC Review & Latency Benchmarks',
    callPurpose: 'Technical walkthrough of failover benchmarks with Marcus Vance',
    priority: 'High',
    status: 'Scheduled',
    date: '2026-09-29',
    time: '10:30',
    durationMinutes: 45,
    direction: 'outbound',
    outcomeStatus: 'Scheduled',
    companyId: 'comp-1',
    contactId: 'con-1',
    assignedUserId: 'user-3', // Alex Rivera
    notes: 'Marcus and DevOps leads attending. Present latency failover test results under load.',
    scriptId: 'script-1',
    scheduledCalendarEventId: 'evt-call-cscale',
    isScheduled: true,
    isCompleted: false,
    createdAt: '2026-09-27T16:00:00Z',
    updatedAt: '2026-09-27T16:00:00Z',
  },
  {
    id: 'call-8',
    subject: 'Quantum Robotics EMEA Hub Onboarding Check-in',
    callPurpose: 'Quarterly review with London robotics division',
    priority: 'Medium',
    status: 'Scheduled',
    date: '2026-09-29',
    time: '14:00',
    durationMinutes: 30,
    direction: 'outbound',
    outcomeStatus: 'Scheduled',
    companyId: 'comp-5',
    assignedUserId: 'user-6', // Sarah Ali
    externalName: 'Arthur Pendelton',
    externalPhone: '+44 20 7946 0912',
    notes: 'Review precision robotic assembly telematics reports and upcoming sensor expansion.',
    scheduledCalendarEventId: 'evt-call-qrobotics',
    isScheduled: true,
    isCompleted: false,
    createdAt: '2026-09-26T11:00:00Z',
    updatedAt: '2026-09-26T11:00:00Z',
  },
  {
    id: 'call-9',
    subject: 'ABC Ltd Technical Sandbox Walkthrough',
    callPurpose: 'Walkthrough API integration environment and data ingestion pipelines',
    priority: 'Medium',
    status: 'Scheduled',
    date: '2026-09-30',
    time: '11:00',
    durationMinutes: 45,
    direction: 'outbound',
    outcomeStatus: 'Scheduled',
    companyId: 'comp-abc',
    contactId: 'con-john-client',
    assignedUserId: 'user-7', // Rahul Das
    notes: 'Provide John and his technical team with sandbox API credentials and sample data sets.',
    isScheduled: true,
    isCompleted: false,
    createdAt: '2026-09-27T18:00:00Z',
    updatedAt: '2026-09-27T18:00:00Z',
  },
  {
    id: 'call-10',
    subject: 'Rescheduled: Global Fleet Analytics Dispatch Algorithm',
    callPurpose: 'Rescheduled demo for dispatch scheduling algorithm',
    priority: 'Low',
    status: 'Rescheduled',
    date: '2026-10-01',
    time: '15:00',
    durationMinutes: 45,
    direction: 'outbound',
    outcomeStatus: 'Rescheduled',
    companyId: 'comp-3',
    contactId: 'con-3',
    assignedUserId: 'user-2', // David Ross
    notes: '[Rescheduled from 26 Sep]: Client was traveling for freight expo conference.',
    scheduledCalendarEventId: 'evt-call-nexus',
    isScheduled: true,
    isCompleted: false,
    createdAt: '2026-09-24T11:00:00Z',
    updatedAt: '2026-09-26T16:00:00Z',
  },
  {
    id: 'call-11',
    subject: 'Cold Inbound Inquiry: Nordic Tech Solutions',
    callPurpose: 'Inbound pricing tiers review for 50 licenses',
    priority: 'Medium',
    status: 'Pending',
    dueDate: '2026-09-28',
    date: '2026-09-28',
    time: '13:30',
    durationMinutes: 15,
    direction: 'inbound',
    outcomeStatus: 'Pending',
    externalName: 'Mark Lindqvist',
    externalPhone: '+46 8 123 4567',
    assignedUserId: 'user-1', // Sarah Jenkins
    notes: 'Interested in API Workflow Suite pricing tiers for 50 users. Inbound web form submission.',
    scriptId: 'script-1',
    isScheduled: false,
    isCompleted: false,
    createdAt: '2026-09-28T08:00:00Z',
    updatedAt: '2026-09-28T08:00:00Z',
  },
  {
    id: 'call-12',
    subject: 'Discovery check-in with Marcus Vance',
    callPurpose: 'Confirm multi-cloud requirements and compliance framework',
    priority: 'High',
    status: 'Completed',
    date: '2026-09-25',
    time: '14:00',
    durationMinutes: 30,
    direction: 'outbound',
    outcomeStatus: 'Connected - Scheduled Demo',
    outcomeNotes: 'Discussed architectural fit. Marcus scheduled architecture review meeting for next week.',
    durationSeconds: 740,
    companyId: 'comp-1',
    contactId: 'con-1',
    assignedUserId: 'user-3', // Alex Rivera
    notes: 'Budget is approved for $120k ARR. Demo planned with core engineering leads.',
    scriptId: 'script-1',
    scriptAnswers: {
      'el-2': 'Yes',
      'el-3': 'Security & Compliance (SOC2/HIPAA)',
      'el-4': 'Immediate (< 1 month)',
    },
    followUpDate: '2026-09-29',
    nextAction: 'Schedule Meeting',
    isScheduled: true,
    isCompleted: true,
    createdAt: '2026-09-25T14:00:00Z',
    updatedAt: '2026-09-25T14:15:00Z',
  },
  {
    id: 'call-13',
    subject: 'Initial intro call with Rachel Sterling (FinEdge)',
    callPurpose: 'Qualify compliance tools pipeline timeline',
    priority: 'Medium',
    status: 'Completed',
    date: '2026-09-24',
    time: '11:00',
    durationMinutes: 15,
    direction: 'outbound',
    outcomeStatus: 'Connected - Interested',
    outcomeNotes: 'Rachel is interested in enterprise tier. Sent security brochure and schedule follow-up.',
    durationSeconds: 520,
    companyId: 'comp-4',
    contactId: 'con-4',
    assignedUserId: 'user-3', // Alex Rivera
    notes: 'Qualified timeline for security audit deployment before end of Q4.',
    followUpDate: '2026-09-26',
    nextAction: 'Follow-up Call',
    isScheduled: false,
    isCompleted: true,
    createdAt: '2026-09-24T11:00:00Z',
    updatedAt: '2026-09-24T11:10:00Z',
  },
];

export const initialTargets: Target[] = [
  {
    id: 'tar-1',
    name: 'Q3 Enterprise Revenue Target',
    description: 'Quarterly sales revenue target across North America enterprise cloud contracts and expansion licenses.',
    type: 'revenue',
    goalValue: 500000,
    currency: 'USD',
    period: 'quarter',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    department: 'Sales & Revenue',
    priority: 'Critical',
    status: 'On Track',
    assignedUserIds: ['user-2', 'user-3', 'user-6'],
    createdBy: 'user-1',
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-09-10T17:05:00Z',
    history: [
      {
        id: 'th-1',
        targetId: 'tar-1',
        timestamp: '2026-07-01T08:30:00Z',
        actorId: 'user-1',
        actorName: 'Sarah Jenkins',
        action: 'created',
        details: 'Created Q3 Enterprise Revenue Target with initial quota of $450,000.',
        newValue: 450000,
      },
      {
        id: 'th-2',
        targetId: 'tar-1',
        timestamp: '2026-08-15T11:00:00Z',
        actorId: 'user-2',
        actorName: 'David Ross',
        action: 'value_changed',
        details: 'Increased target quota from $450,000 to $500,000 following territory expansion.',
        oldValue: 450000,
        newValue: 500000,
      },
      {
        id: 'th-3',
        targetId: 'tar-1',
        timestamp: '2026-09-01T09:00:00Z',
        actorId: 'user-2',
        actorName: 'David Ross',
        action: 'members_changed',
        details: 'Added Sarah Ali (user-6) to target team members roster.',
      },
      {
        id: 'th-4',
        targetId: 'tar-1',
        timestamp: '2026-09-10T17:05:00Z',
        actorId: 'user-2',
        actorName: 'David Ross',
        action: 'updated',
        details: 'Logged Nexus Fleet closed won deal ($58,000). System updated achievement.',
      },
    ],
    notificationsConfig: {
      onAssignment: true,
      onMilestone: true,
      onApproachingDeadline: true,
      onFallingBehind: true,
    },
  },
  {
    id: 'tar-2',
    name: 'September Customer Support Ticket Resolution',
    description: 'Monthly resolution quota for customer support tickets, prioritizing critical SLAs and customer satisfaction.',
    type: 'cases_resolved',
    goalValue: 20,
    currency: 'USD',
    period: 'month',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    department: 'Customer Success',
    priority: 'High',
    status: 'Active',
    assignedUserIds: ['user-4'],
    createdBy: 'user-1',
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-15T15:00:00Z',
    history: [
      {
        id: 'th-5',
        targetId: 'tar-2',
        timestamp: '2026-09-01T08:00:00Z',
        actorId: 'user-1',
        actorName: 'Sarah Jenkins',
        action: 'created',
        details: 'Created September Customer Support Resolution target for Customer Success team.',
        newValue: 20,
      },
    ],
    notificationsConfig: {
      onAssignment: true,
      onMilestone: true,
      onApproachingDeadline: true,
      onFallingBehind: false,
    },
  },
  {
    id: 'tar-3',
    name: 'Q3 Enterprise Software Units Closed',
    description: 'Volume target tracking number of multi-tenant enterprise software and hardware gateway packages sold.',
    type: 'units_sold',
    goalValue: 8,
    currency: 'USD',
    period: 'quarter',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    department: 'Sales & Revenue',
    priority: 'Medium',
    status: 'At Risk',
    assignedUserIds: ['user-2', 'user-3', 'user-5'],
    createdBy: 'user-2',
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-09-10T17:00:00Z',
    history: [
      {
        id: 'th-6',
        targetId: 'tar-3',
        timestamp: '2026-07-01T09:00:00Z',
        actorId: 'user-2',
        actorName: 'David Ross',
        action: 'created',
        details: 'Created Q3 software units closed target for commercial sales reps.',
        newValue: 8,
      },
    ],
    notificationsConfig: {
      onAssignment: true,
      onMilestone: true,
      onApproachingDeadline: true,
      onFallingBehind: true,
    },
  },
  {
    id: 'tar-4',
    name: 'Q3 Strategic Enterprise Deals Closed',
    description: 'Track count of successfully closed deals for enterprise clients across all reps.',
    type: 'deals_closed',
    goalValue: 5,
    currency: 'USD',
    period: 'quarter',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    department: 'Sales & Revenue',
    priority: 'High',
    status: 'On Track',
    assignedUserIds: ['user-2', 'user-3', 'user-6'],
    createdBy: 'user-1',
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-09-10T17:00:00Z',
    history: [
      {
        id: 'th-7',
        targetId: 'tar-4',
        timestamp: '2026-07-01T10:00:00Z',
        actorId: 'user-1',
        actorName: 'Sarah Jenkins',
        action: 'created',
        details: 'Target initialized for closed enterprise deals quota.',
        newValue: 5,
      },
    ],
    notificationsConfig: {
      onAssignment: true,
      onMilestone: true,
      onApproachingDeadline: true,
      onFallingBehind: true,
    },
  },
  {
    id: 'tar-5',
    name: 'Q3 New Strategic Customers Acquired',
    description: 'Net new customer accounts converted from qualified lead pipeline.',
    type: 'new_customers',
    goalValue: 6,
    currency: 'USD',
    period: 'quarter',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    department: 'Sales & Revenue',
    priority: 'Medium',
    status: 'On Track',
    assignedUserIds: ['user-2', 'user-3', 'user-6'],
    createdBy: 'user-1',
    createdAt: '2026-07-01T10:30:00Z',
    updatedAt: '2026-08-20T12:00:00Z',
    history: [
      {
        id: 'th-8',
        targetId: 'tar-5',
        timestamp: '2026-07-01T10:30:00Z',
        actorId: 'user-1',
        actorName: 'Sarah Jenkins',
        action: 'created',
        details: 'Created Q3 New Customer Acquisition target.',
        newValue: 6,
      },
    ],
    notificationsConfig: {
      onAssignment: true,
      onMilestone: true,
      onApproachingDeadline: false,
      onFallingBehind: true,
    },
  },
  {
    id: 'tar-6',
    name: 'Customer Net Promoter Score (NPS)',
    description: 'Overall executive client satisfaction rating measured by post-implementation survey submissions.',
    type: 'custom_kpi',
    customKpiName: 'NPS Index',
    customKpiUnit: 'Points',
    goalValue: 85,
    manualAchievement: 88,
    currency: 'USD',
    period: 'quarter',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    department: 'Customer Success',
    priority: 'Critical',
    status: 'Completed',
    assignedUserIds: ['user-4', 'user-1'],
    createdBy: 'user-1',
    createdAt: '2026-07-01T11:00:00Z',
    updatedAt: '2026-09-20T14:30:00Z',
    history: [
      {
        id: 'th-9',
        targetId: 'tar-6',
        timestamp: '2026-07-01T11:00:00Z',
        actorId: 'user-1',
        actorName: 'Sarah Jenkins',
        action: 'created',
        details: 'Established quarterly Custom KPI for Client NPS Index.',
        newValue: 85,
      },
      {
        id: 'th-10',
        targetId: 'tar-6',
        timestamp: '2026-09-20T14:30:00Z',
        actorId: 'user-4',
        actorName: 'Elena Rostova',
        action: 'achievement_overridden',
        details: 'Updated manual score to 88 points based on latest quarterly audit responses.',
        oldValue: 80,
        newValue: 88,
      },
    ],
    notificationsConfig: {
      onAssignment: true,
      onMilestone: true,
      onApproachingDeadline: false,
      onFallingBehind: false,
    },
  },
  {
    id: 'tar-7',
    name: 'Q4 Early Pipeline Expansion Quota',
    description: 'Upcoming Q4 revenue target for newly onboarded sales representatives and senior account executives.',
    type: 'revenue',
    goalValue: 750000,
    currency: 'USD',
    period: 'quarter',
    startDate: '2026-10-01',
    endDate: '2026-12-31',
    department: 'Sales & Revenue',
    priority: 'High',
    status: 'Upcoming',
    assignedUserIds: ['user-2', 'user-3', 'user-5', 'user-6'],
    createdBy: 'user-1',
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
    history: [
      {
        id: 'th-11',
        targetId: 'tar-7',
        timestamp: '2026-09-20T10:00:00Z',
        actorId: 'user-1',
        actorName: 'Sarah Jenkins',
        action: 'created',
        details: 'Defined upcoming Q4 enterprise revenue target.',
        newValue: 750000,
      },
    ],
    notificationsConfig: {
      onAssignment: true,
      onMilestone: true,
      onApproachingDeadline: true,
      onFallingBehind: true,
    },
  },
];

export const initialFolders: Folder[] = [
  { id: 'fld-root', name: 'Root Folder', description: 'Master CRM repository', parentId: null },
  { id: 'fld-sales', name: 'Sales Collateral & Proposals', description: 'Decks, pricing sheets, case studies', parentId: 'fld-root' },
  { id: 'fld-legal', name: 'Legal Agreements & BAAs', description: 'Standard MSA, NDAs, HIPAA agreements', parentId: 'fld-root' },
  { id: 'fld-clients', name: 'Client Shared Folders', description: 'Dedicated documentation per company', parentId: 'fld-root' },
];

export const initialDocuments: DocumentFile[] = [
  {
    id: 'doc-1',
    title: 'Apex Cloud Platform Architecture Whitepaper',
    description: 'Technical overview of zero-trust microservice architecture and fault tolerance.',
    version: '2.4',
    folderId: 'fld-sales',
    fileName: 'Apex_Architecture_Whitepaper_v2.4.pdf',
    fileSize: 3450000,
    fileType: 'application/pdf',
    companyId: 'comp-1',
    uploadedBy: 'Sarah Jenkins',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-02T14:00:00Z',
  },
  {
    id: 'doc-2',
    title: 'Standard HIPAA Business Associate Agreement (BAA)',
    description: 'Updated template compliant with HITECH and HHS enforcement rules.',
    version: '1.2',
    folderId: 'fld-legal',
    fileName: 'Apex_BAA_Agreement_Template.docx',
    fileSize: 890000,
    fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    companyId: 'comp-2',
    uploadedBy: 'David Ross',
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-09-14T09:00:00Z',
  },
  {
    id: 'doc-3',
    title: 'Telematics Fleet Gateway Installation Manual',
    description: 'Hardware wiring schematics and OBD-II pairing guide for vehicle technicians.',
    version: '3.0',
    folderId: 'fld-clients',
    fileName: 'Nexus_Telematics_Manual_v3.pdf',
    fileSize: 5200000,
    fileType: 'application/pdf',
    companyId: 'comp-3',
    uploadedBy: 'Elena Rostova',
    createdAt: '2026-09-01T15:00:00Z',
    updatedAt: '2026-09-01T15:00:00Z',
  },
];

export const initialEmailAccounts: EmailAccount[] = [
  {
    id: 'ea-1',
    name: 'Apex Sales Sync Mailbox',
    email: 'sales@apexsolutions.example.com',
    provider: 'Google Workspace',
    status: 'connected',
    lastSyncedAt: '2026-09-17T07:25:00Z',
  },
  {
    id: 'ea-2',
    name: 'Support Operations Mailbox',
    email: 'support@apexsolutions.example.com',
    provider: 'Microsoft 365',
    status: 'connected',
    lastSyncedAt: '2026-09-17T07:10:00Z',
  },
];

export const initialEmailMessages: EmailMessage[] = [
  {
    id: 'em-1',
    accountId: 'ea-1',
    subject: 'Re: CloudScale - Security Questionnaire response & next steps',
    sender: 'm.vance@cloudscalenetworks.example.com',
    recipient: 'sales@apexsolutions.example.com',
    body: 'Hi Alex, our SecOps lead reviewed your responses and was pleased with the multi-region failover benchmarks. Looking forward to our call this Thursday at 10 AM.',
    timestamp: '2026-09-16T18:24:00Z',
    attachedTo: {
      type: 'contact',
      id: 'con-1',
      name: 'Marcus Vance',
    },
  },
  {
    id: 'em-2',
    accountId: 'ea-1',
    subject: 'BioVance Contract - Section 4 redline comments',
    sender: 'ereed@biovancehealth.example.com',
    recipient: 'sales@apexsolutions.example.com',
    body: 'Alex, attached are our internal legal counsel markups on the BAA. The primary point is around audit notification windows. Can we discuss on Friday?',
    timestamp: '2026-09-16T14:15:00Z',
    attachedTo: {
      type: 'company',
      id: 'comp-2',
      name: 'BioVance Health Labs',
    },
  },
  {
    id: 'em-3',
    accountId: 'ea-2',
    subject: 'Case #CASE-1 Inbound webhook latency notice',
    sender: 'ops@cloudscalenetworks.example.com',
    recipient: 'support@apexsolutions.example.com',
    body: 'We noticed response times spiked above 1800ms between 14:00 - 15:30. Opening ticket for urgent review.',
    timestamp: '2026-09-16T15:35:00Z',
    attachedTo: {
      type: 'case',
      id: 'case-1',
      name: 'Inbound Webhook latency degradation',
    },
  },
];

export const initialEmailTemplates: EmailTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Executive Discovery Follow-up',
    subject: 'Following up on our discussion regarding {{company.name}}',
    body: `Hello {{contact.firstName}},

Thank you for taking the time to speak with me earlier today. Based on our conversation regarding {{company.name}}, I've assembled the architecture overview and pricing details for your review.

Please let me know if you would like to schedule a 30-minute technical session with our solution architects next week.

Warm regards,
{{user.name}}
{{user.email}}
Apex Global Solutions`,
    createdAt: '2026-08-10T00:00:00Z',
  },
  {
    id: 'tmpl-2',
    name: 'New Product Announcement - AI Workflow Suite',
    subject: 'Accelerate your operations with the new AI Workflow Suite',
    body: `Hi {{contact.firstName}},

We are thrilled to announce the launch of our next-generation AI Workflow Suite, purpose-built to streamline data transformation and compliance audits for leaders in {{company.industry}}.

Click here to explore the interactive sandbox or book a personalized demonstration.

Best,
The Apex Solutions Team`,
    createdAt: '2026-08-15T00:00:00Z',
  },
];

export const initialCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    title: 'Q3 Enterprise Cloud Modernization Outreach',
    schedule: 'one-off',
    templateId: 'tmpl-2',
    sendingAccountId: 'ea-1',
    status: 'sent',
    sentCount: 148,
    openedCount: 92,
    clickedCount: 44,
    bouncedCount: 2,
    recipientContactIds: ['con-1', 'con-2', 'con-4'],
    sentAt: '2026-09-12T14:00:00Z',
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'camp-2',
    title: 'Automated Post-Support Case Satisfaction Survey',
    schedule: 'recurring',
    templateId: 'tmpl-1',
    sendingAccountId: 'ea-2',
    status: 'scheduled',
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    bouncedCount: 0,
    recipientContactIds: ['con-3'],
    createdAt: '2026-09-15T11:00:00Z',
  },
];

export const initialCustomForms: CustomForm[] = [
  {
    id: 'form-1',
    title: 'Enterprise Technical Qualification & Needs Intake',
    description: 'Intake form for new prospective client technical architects and procurement teams.',
    instructions: 'Please answer the following questions to help our solution team size your implementation.',
    isPublic: true,
    questions: [
      { id: 'q-1', prompt: 'What is your primary cloud platform provider?', type: 'multiple_choice', options: ['AWS', 'Google Cloud', 'Microsoft Azure', 'On-premises / Hybrid'], required: true },
      { id: 'q-2', prompt: 'Estimated monthly active transactions or records:', type: 'free_text', required: true },
      { id: 'q-3', prompt: 'Do you require dedicated HIPAA or SOC2 Type II compliance validation?', type: 'yes_no', required: true },
      { id: 'q-4', prompt: 'Target implementation go-live date:', type: 'date', required: false },
    ],
    submissions: [
      {
        id: 'sub-1',
        contactId: 'con-1',
        responderName: 'Marcus Vance',
        responderEmail: 'm.vance@cloudscalenetworks.example.com',
        answers: {
          'q-1': 'Google Cloud',
          'q-2': '25 Million records/month',
          'q-3': 'Yes',
          'q-4': '2026-10-15',
        },
        submittedAt: '2026-09-12T16:20:00Z',
      },
    ],
    createdAt: '2026-08-20T00:00:00Z',
  },
];

export const initialMessageThreads: MessageThread[] = [
  {
    id: 'msg-1',
    title: 'Q3 Closing Sprint: Target Attainment & Celebration',
    content: 'Team, with our Nexus deal won and BioVance in final contract negotiations, we are at 67% of our quarterly revenue target with two weeks remaining. Let us keep the momentum high and clear remaining customer verification roadblocks!',
    authorId: 'user-2',
    authorName: 'David Ross',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-15T09:00:00Z',
    attachedDocuments: [
      {
        id: 'doc-1',
        title: 'Apex Cloud Platform Architecture Whitepaper',
        fileName: 'Apex_Architecture_Whitepaper_v2.4.pdf',
        fileSize: 3450000,
        fileType: 'application/pdf',
        version: '2.4',
        folderId: 'fld-sales',
      },
    ],
    replies: [
      {
        id: 'rep-1',
        authorId: 'user-3',
        authorName: 'Alex Rivera',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        text: 'CloudScale presentation deck is looking great too! If we close both BioVance and CloudScale, we exceed 100% of goal.',
        createdAt: '2026-09-15T09:30:00Z',
      },
      {
        id: 'rep-2',
        authorId: 'user-1',
        authorName: 'Sarah Jenkins',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        text: 'Awesome execution everyone. Let me know if you need any executive sponsorship on either call this week.',
        createdAt: '2026-09-15T10:15:00Z',
      },
    ],
  },
  {
    id: 'msg-2',
    title: 'Updated Call Scripts & Compliance Guidance for Financial Accounts',
    content: 'We updated Script #1 to include compliance questions regarding SEC/FINRA log encryption. Please review before dialing FinEdge or wealth advisory leads.',
    authorId: 'user-1',
    authorName: 'Sarah Jenkins',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-14T11:00:00Z',
    replies: [],
  },
];

export const initialDirectMessages: DirectMessage[] = [
  {
    id: 'dm-1',
    senderId: 'user-3',
    senderName: 'Alex Rivera',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-1',
    recipientName: 'Sarah Jenkins',
    recipientAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    text: 'Hi Sarah, Dr. Evelyn Reed at BioVance requested an updated BAA clause for the diagnostic AI license. Are we cleared to issue the revised addendum?',
    createdAt: '2026-09-16T14:15:00Z',
    read: true,
    relatedRecord: {
      type: 'deal',
      id: 'deal-2',
      title: 'BioVance Diagnostic Platform AI Licensing',
    },
  },
  {
    id: 'dm-2',
    senderId: 'user-1',
    senderName: 'Sarah Jenkins',
    senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-3',
    recipientName: 'Alex Rivera',
    recipientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    text: 'Yes, approved! Use the standard tier-2 compliance addendum from Documents. Ping me if you need executive sponsorship during their legal signoff.',
    createdAt: '2026-09-16T14:22:00Z',
    read: true,
    attachedDocuments: [
      {
        id: 'doc-2',
        title: 'Standard HIPAA Business Associate Agreement (BAA)',
        fileName: 'Apex_BAA_Agreement_Template.docx',
        fileSize: 890000,
        fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        version: '1.2',
        folderId: 'fld-legal',
      },
    ],
  },
  {
    id: 'dm-3',
    senderId: 'user-3',
    senderName: 'Alex Rivera',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-1',
    recipientName: 'Sarah Jenkins',
    recipientAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    text: 'Awesome, sent the packet over to Dr. Reed and scheduled our confirmation call.',
    createdAt: '2026-09-16T14:40:00Z',
    read: true,
  },
  {
    id: 'dm-4',
    senderId: 'user-2',
    senderName: 'David Ross',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-4',
    recipientName: 'Elena Rostova',
    recipientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    text: 'Hi Elena, how is the onboarding going for CloudScale Networks? Did they configure their telemetry webhook endpoints?',
    createdAt: '2026-09-17T09:10:00Z',
    read: true,
    relatedRecord: {
      type: 'company',
      id: 'comp-1',
      title: 'CloudScale Networks',
    },
  },
  {
    id: 'dm-5',
    senderId: 'user-4',
    senderName: 'Elena Rostova',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-2',
    recipientName: 'David Ross',
    recipientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    text: 'Hey David! Marcus Vance confirmed their engineering team finished testing the staging endpoint. All green for production rollout next Tuesday!',
    createdAt: '2026-09-17T09:35:00Z',
    read: false,
  },
  {
    id: 'dm-6',
    senderId: 'user-2',
    senderName: 'David Ross',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    recipientId: 'user-1',
    recipientName: 'Sarah Jenkins',
    recipientAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    text: 'Sarah, let us review the regional targets for NA-East this afternoon before the weekly pipeline review.',
    createdAt: '2026-09-17T11:00:00Z',
    read: true,
  },
];

export const defaultResourceCategories = [
  'Partner Links',
  'Vendor Links',
  'Customer Websites',
  'Legal Documents',
  'Company Policies',
  'Procedures',
  'Training',
  'Internal Information',
  'Useful Websites',
  'Other',
];

export const initialSharedResources: SharedResource[] = [
  {
    id: 'res-partner-portal',
    title: 'Partner Portal',
    type: 'hyperlink',
    url: 'https://partners.apexcloud.example.com',
    description: 'Quick access to the partner portal for co-selling deals, deal registration, and partner tier benefits.',
    category: 'Partner Links',
    tags: ['Partners', 'Portal', 'Channel'],
    visibility: 'everyone',
    isPinned: true,
    isFavorite: true,
    createdBy: 'Sarah Jenkins',
    createdById: 'user-1',
    createdAt: '2026-08-01T09:00:00Z',
    lastModifiedBy: 'Sarah Jenkins',
    lastModifiedAt: '2026-09-15T10:30:00Z',
    viewsCount: 184,
    lastAccessedAt: '2026-09-28T06:15:00Z',
  },
  {
    id: 'res-support-guide',
    title: 'Customer Support Instructions',
    type: 'text',
    description: 'Standard operational procedure for triaging and resolving inbound customer tickets.',
    category: 'Procedures',
    content: `### Customer Support Instructions

Step 1: **Verify the customer's account**
* Check company contract tier, active support SLA (Standard vs 24/7 Enterprise), and primary contact email.
* Ensure account is not in suspended billing status.

Step 2: **Check the previous support history**
* Review prior closed and in-progress tickets in the **Cases & Support** module.
* Note any known outages or recurring bug reports.

Step 3: **Record the resolution in the CRM**
* Document exact steps taken, root cause, and time-to-resolution.
* Send follow-up confirmation email to the client contact.
* Update ticket status to **Closed** or **Pending Customer Confirmation**.`,
    tags: ['Support', 'Instructions', 'SLA', 'Procedures'],
    visibility: 'everyone',
    isPinned: true,
    isFavorite: false,
    createdBy: 'David Ross',
    createdById: 'user-2',
    createdAt: '2026-08-12T14:20:00Z',
    lastModifiedBy: 'David Ross',
    lastModifiedAt: '2026-09-20T11:00:00Z',
    viewsCount: 142,
    lastAccessedAt: '2026-09-28T07:10:00Z',
  },
  {
    id: 'res-msa-template',
    title: 'Enterprise Master Services Agreement (MSA) v3.2',
    type: 'document',
    description: 'Official legal contract template for enterprise software licensing with standard warranty and indemnity terms.',
    category: 'Legal Documents',
    fileName: 'Apex_Enterprise_MSA_Template_v3.2.pdf',
    fileSize: '2.4 MB',
    fileType: 'application/pdf',
    documentVersion: 'v3.2',
    tags: ['Legal', 'Contracts', 'MSA', 'Compliance'],
    visibility: 'everyone',
    isPinned: true,
    isFavorite: true,
    createdBy: 'Sarah Jenkins',
    createdById: 'user-1',
    createdAt: '2026-08-15T10:00:00Z',
    lastModifiedBy: 'Sarah Jenkins',
    lastModifiedAt: '2026-09-10T16:00:00Z',
    viewsCount: 96,
    lastAccessedAt: '2026-09-27T15:20:00Z',
  },
  {
    id: 'res-sales-playbook',
    title: 'Sales Objection Handling & Discovery Playbook',
    type: 'text',
    description: 'Battlecards, competitive differentiators, and scripts for cloud migration discovery calls.',
    category: 'Training',
    content: `### Sales Discovery & Objection Playbook

#### Key Discovery Questions
1. *What is your current multi-region failover latency and disaster recovery SLA?*
2. *How many team hours are spent every quarter on SOC2 and compliance audits?*
3. *What is the projected database growth over the next 12 months?*

#### Top 3 Objections & Answers
* **Objection 1**: *"We already use native AWS/GCP tools"*
  * **Counter**: Highlight our unified cross-cloud control plane, audit trail aggregation, and 35% reduced egress costs.
* **Objection 2**: *"Our rollout timeline is next fiscal year"*
  * **Counter**: Offer our zero-friction 14-day telemetry sandbox which requires no production reconfigurations.
* **Objection 3**: *"We need formal infosec approval"*
  * **Counter**: Instantly share our pre-filled SIG Lite assessment and SOC2 Type II packet.`,
    tags: ['Sales', 'Playbook', 'Objections', 'Training'],
    visibility: 'team',
    isPinned: false,
    isFavorite: true,
    createdBy: 'Alex Rivera',
    createdById: 'user-3',
    createdAt: '2026-08-20T16:30:00Z',
    lastModifiedBy: 'David Ross',
    lastModifiedAt: '2026-09-18T13:45:00Z',
    viewsCount: 118,
    lastAccessedAt: '2026-09-28T05:40:00Z',
  },
  {
    id: 'res-aws-marketplace',
    title: 'AWS Partner Central & Marketplace Billing',
    type: 'quicklink',
    url: 'https://partnercentral.awspartner.com',
    description: 'Fast link to submit CPPO discount authorizations and track marketplace private contracts.',
    category: 'Vendor Links',
    tags: ['AWS', 'Marketplace', 'Vendor', 'Billing'],
    visibility: 'everyone',
    isPinned: false,
    isFavorite: false,
    createdBy: 'Sarah Jenkins',
    createdById: 'user-1',
    createdAt: '2026-08-25T11:00:00Z',
    lastModifiedBy: 'Sarah Jenkins',
    lastModifiedAt: '2026-08-25T11:00:00Z',
    viewsCount: 65,
    lastAccessedAt: '2026-09-26T14:10:00Z',
  },
  {
    id: 'res-soc2-report',
    title: 'Annual SOC2 Type II Audit Attestation Report',
    type: 'document',
    description: 'Latest third-party auditor report validating security, availability, and confidentiality controls.',
    category: 'Company Policies',
    fileName: 'Apex_SOC2_Type_II_Audit_2026.pdf',
    fileSize: '4.8 MB',
    fileType: 'application/pdf',
    documentVersion: '2026.1',
    tags: ['Security', 'SOC2', 'Audit', 'Infosec'],
    visibility: 'everyone',
    isPinned: false,
    isFavorite: true,
    createdBy: 'Sarah Jenkins',
    createdById: 'user-1',
    createdAt: '2026-08-28T09:15:00Z',
    lastModifiedBy: 'Sarah Jenkins',
    lastModifiedAt: '2026-09-01T10:00:00Z',
    viewsCount: 152,
    lastAccessedAt: '2026-09-28T04:20:00Z',
  },
  {
    id: 'res-sec-compliance',
    title: 'Official SEC Rule 17a-4 Electronic Records Checklist',
    type: 'hyperlink',
    url: 'https://www.sec.gov/rules/final/34-47806.htm',
    description: 'Regulatory requirements reference guide for broker-dealer communications archiving.',
    category: 'Internal Information',
    tags: ['SEC', 'Compliance', 'Regulatory'],
    visibility: 'everyone',
    isPinned: false,
    isFavorite: false,
    createdBy: 'Sarah Jenkins',
    createdById: 'user-1',
    createdAt: '2026-08-10T12:00:00Z',
    lastModifiedBy: 'Sarah Jenkins',
    lastModifiedAt: '2026-08-10T12:00:00Z',
    viewsCount: 41,
    lastAccessedAt: '2026-09-21T09:00:00Z',
  },
  {
    id: 'res-biovance-spec',
    title: 'BioVance API & Telemetry Webhook Specification',
    type: 'document',
    description: 'Technical schemas and webhook payload validation guide for customer engineering integration.',
    category: 'Customer Websites',
    fileName: 'BioVance_API_Telemetry_Spec_v2.0.docx',
    fileSize: '1.2 MB',
    fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    documentVersion: 'v2.0',
    tags: ['BioVance', 'API', 'Webhooks', 'Specs'],
    visibility: 'team',
    isPinned: false,
    isFavorite: false,
    createdBy: 'Elena Rostova',
    createdById: 'user-4',
    createdAt: '2026-09-05T13:40:00Z',
    lastModifiedBy: 'Elena Rostova',
    lastModifiedAt: '2026-09-12T16:15:00Z',
    viewsCount: 38,
    lastAccessedAt: '2026-09-25T11:30:00Z',
  },
  {
    id: 'res-crm-mapping',
    title: 'CRM Data Field Migration Matrix',
    type: 'quicklink',
    url: 'https://docs.google.com/spreadsheets/d/1example-crm-mapping',
    description: 'Google Sheets schema mapping legacy fields and contacts to our unified CRM schema.',
    category: 'Useful Websites',
    tags: ['Migration', 'Sheets', 'CRM', 'Data'],
    visibility: 'private',
    isPinned: false,
    isFavorite: false,
    createdBy: 'Sarah Jenkins',
    createdById: 'user-1',
    createdAt: '2026-09-08T08:30:00Z',
    lastModifiedBy: 'Sarah Jenkins',
    lastModifiedAt: '2026-09-08T08:30:00Z',
    viewsCount: 22,
    lastAccessedAt: '2026-09-20T14:45:00Z',
  },
];

export const initialAuditLogs: AuditLogItem[] = [
  {
    id: 'log-1',
    actorId: 'user-1',
    actorName: 'Sarah Jenkins',
    action: 'ORGANISATION_SETUP',
    details: 'Configured organisation profile and set global sharing policy to all_shared',
    timestamp: '2026-08-01T08:00:00Z',
  },
  {
    id: 'log-2',
    actorId: 'user-1',
    actorName: 'Sarah Jenkins',
    action: 'USER_CREATED',
    details: 'Provisioned user accounts for David Ross (Manager) and Alex Rivera (Standard)',
    timestamp: '2026-08-01T09:30:00Z',
  },
  {
    id: 'log-3',
    actorId: 'user-2',
    actorName: 'David Ross',
    action: 'TARGET_CREATED',
    details: 'Created target "Q3 Enterprise Revenue Target" ($450,000 goal)',
    timestamp: '2026-07-01T10:00:00Z',
  },
  {
    id: 'log-4',
    actorId: 'user-3',
    actorName: 'Alex Rivera',
    action: 'DEAL_UPDATED',
    details: 'Moved "BioVance Diagnostic Platform AI Licensing" to Negotiation stage',
    timestamp: '2026-09-14T10:15:00Z',
  },
  {
    id: 'log-5',
    actorId: 'user-1',
    actorName: 'Sarah Jenkins',
    action: 'BULK_EXPORT',
    details: 'Exported 14 records from Companies and Contacts combined (CSV, comma-delimited)',
    timestamp: '2026-09-16T17:00:00Z',
  },
];

export const initialSavedViews: SavedCustomView[] = [
  // Company Views
  {
    id: 'view-comp-all',
    title: 'All Companies',
    module: 'company',
    entity: 'company',
    columns: ['name', 'industry', 'priority', 'owner', 'phone', 'city'],
    filters: {},
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'Complete overview of all active organisation accounts and clients.',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'view-comp-active',
    title: 'Active Companies',
    module: 'company',
    entity: 'company',
    columns: ['name', 'industry', 'phone', 'email', 'city', 'priority'],
    filters: {
      status: 'Active',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'Companies with active relationships across high, medium, and critical tiers.',
    createdAt: '2026-08-02T09:00:00Z',
    updatedAt: '2026-08-02T09:00:00Z',
  },
  {
    id: 'view-comp-key-accounts',
    title: 'High Priority Accounts',
    module: 'company',
    entity: 'company',
    columns: ['name', 'industry', 'annualRevenue', 'priority', 'owner', 'phone', 'city'],
    filters: {
      priority: 'High',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: false,
    description: 'Tier-1 enterprise accounts with high and critical engagement urgency.',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'view-comp-tech',
    title: 'Technology Sector',
    module: 'company',
    entity: 'company',
    columns: ['name', 'industry', 'phone', 'email', 'website', 'city'],
    filters: {
      industry: 'Enterprise Technology',
    },
    userId: 'user-2',
    userName: 'David Ross',
    isShared: true,
    isSystem: false,
    description: 'Enterprise tech and software infrastructure prospects and clients.',
    createdAt: '2026-08-15T11:00:00Z',
    updatedAt: '2026-08-15T11:00:00Z',
  },

  // Contact / Lead / Customer Views
  {
    id: 'view-con-all',
    title: 'All Contacts',
    module: 'contact',
    entity: 'contact',
    columns: ['name', 'company', 'type', 'email', 'phone', 'owner'],
    filters: {},
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'Directory of all people across leads, customers, vendors, and contacts.',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'view-con-leads',
    title: 'Important Leads',
    module: 'contact',
    entity: 'contact',
    columns: ['name', 'jobTitle', 'company', 'email', 'phone', 'type', 'owner'],
    filters: {
      type: 'lead',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'Prospective decision makers and leads currently being qualified.',
    createdAt: '2026-08-05T09:30:00Z',
    updatedAt: '2026-08-05T09:30:00Z',
  },
  {
    id: 'view-con-customers',
    title: 'My Customers',
    module: 'contact',
    entity: 'contact',
    columns: ['name', 'jobTitle', 'company', 'email', 'phone', 'owner'],
    filters: {
      type: 'customer',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: false,
    description: 'Active client accounts and executive customer contacts.',
    createdAt: '2026-08-12T14:00:00Z',
    updatedAt: '2026-08-12T14:00:00Z',
  },

  // Deal Views
  {
    id: 'view-deal-pipeline',
    title: 'Active Pipeline Deals',
    module: 'deal',
    columns: ['title', 'company', 'value', 'stage', 'status', 'expectedCloseDate', 'owner'],
    filters: {
      status: 'open',
    },
    userId: 'user-1',
    userName: 'Sarah Jenkins',
    isShared: true,
    isSystem: true,
    description: 'All currently open sales opportunities moving through the pipeline.',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'view-deal-high-value',
    title: 'High Value Deals ($100k+)',
    module: 'deal',
    columns: ['title', 'company', 'product', 'value', 'stage', 'owner'],
    filters: {
      status: 'open',
    },
    userId: 'user-2',
    userName: 'David Ross',
    isShared: true,
    isSystem: false,
    description: 'Major sales opportunities exceeding standard contract thresholds.',
    createdAt: '2026-08-20T16:00:00Z',
    updatedAt: '2026-08-20T16:00:00Z',
  },
];

export const initialNotifications: CRMNotification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'meeting_invite',
    title: 'New Meeting Invitation',
    message: 'Alex Rivera scheduled "CloudScale Architecture Review & Security Briefing"',
    meetingId: 'evt-1',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'meeting_reminder',
    title: 'Upcoming Meeting Reminder (15 mins)',
    message: 'Weekly Sales Pipeline & Target Review starts in 15 minutes',
    meetingId: 'evt-3',
    read: false,
    createdAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-5', // John Doe
    type: 'meeting_invite',
    title: 'Meeting Scheduled',
    message: 'You have been added to "BioVance BAA Contract & Legal Terms Finalization"',
    meetingId: 'evt-2',
    read: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'notif-4',
    userId: 'user-6', // Sarah Ali
    type: 'meeting_invite',
    title: 'Meeting Confirmed',
    message: 'Confirmed on your calendar: "Client Meeting" at 10:00 AM',
    meetingId: 'evt-conflict-sarah',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const initialMeetingTemplates: MeetingTemplate[] = [
  {
    id: 'tmpl-weekly-sync',
    name: 'Weekly Sync',
    title: 'Weekly Team Sync',
    durationMinutes: 30,
    category: 'team',
    locationType: 'online',
    location: 'Google Meet',
    meetingLink: 'https://meet.google.com/apex-team-sync',
    reminderMinutes: 15,
    description: 'Weekly team check-in to review metrics, active deliverables, and unblock challenges.',
    agenda: '1. Wins & Highlights from the past week (5 mins)\n2. Key KPI & OKR metrics progress (10 mins)\n3. Cross-functional blockers & dependencies (10 mins)\n4. Priorities & deliverables for this week (5 mins)',
    isDefault: true,
  },
  {
    id: 'tmpl-client-discovery',
    name: 'Client Discovery',
    title: 'Client Discovery & Needs Assessment',
    durationMinutes: 45,
    category: 'sales',
    locationType: 'online',
    location: 'Client Zoom / Video Call',
    meetingLink: 'https://meet.google.com/apex-client-discovery',
    reminderMinutes: 15,
    description: 'Initial customer exploratory session to uncover business challenges and workflow fit.',
    agenda: '1. Executive introduction & agenda alignment (5 mins)\n2. Current business landscape & key pain points (15 mins)\n3. Technology stack & workflow review (15 mins)\n4. Evaluation criteria, timeline, and next milestones (10 mins)',
    isDefault: true,
  },
  {
    id: 'tmpl-team-retro',
    name: 'Team Retro',
    title: 'Team Sprint Retrospective',
    durationMinutes: 60,
    category: 'team',
    locationType: 'office',
    location: 'Agile War Room / Main Boardroom',
    meetingLink: 'https://meet.google.com/apex-sprint-retro',
    reminderMinutes: 30,
    description: 'Sprint retrospective to celebrate wins, address blockers, and identify actionable process improvements.',
    agenda: '1. Icebreaker & sprint metrics recap (10 mins)\n2. What went well? (Celebrations & successes) (15 mins)\n3. What could be improved? (Friction & bottlenecks) (15 mins)\n4. Action items & continuous improvement owners (20 mins)',
    isDefault: true,
  },
  {
    id: 'tmpl-product-demo',
    name: 'Product Demo',
    title: 'Product Demo & Solution Walkthrough',
    durationMinutes: 45,
    category: 'sales',
    locationType: 'online',
    location: 'Google Meet Demo Bridge',
    meetingLink: 'https://meet.google.com/apex-demo-walkthrough',
    reminderMinutes: 15,
    description: 'Interactive solution demo tailored to prospective customer business requirements.',
    agenda: '1. Confirm target objectives & user scenarios (5 mins)\n2. Core platform workflow demonstration (25 mins)\n3. Technical architecture, data security & API questions (10 mins)\n4. Next steps & pilot agreement review (5 mins)',
    isDefault: true,
  },
  {
    id: 'tmpl-one-on-one',
    name: '1-on-1 Check-in',
    title: '1-on-1 Sync & Development Check-in',
    durationMinutes: 30,
    category: 'leadership',
    locationType: 'office',
    location: 'Focus Room B / Casual Coffee Lounge',
    meetingLink: '',
    reminderMinutes: 15,
    description: 'Bi-weekly dedicated personal coaching, feedback, and career growth conversation.',
    agenda: '1. Personal pulse check & wellbeing (5 mins)\n2. Current priorities, bandwidth & obstacles (15 mins)\n3. Mutual feedback & leadership support (5 mins)\n4. Actionable next steps & growth goals (5 mins)',
    isDefault: true,
  },
  {
    id: 'tmpl-executive-review',
    name: 'Executive Review',
    title: 'Executive Quarterly Strategy Review',
    durationMinutes: 60,
    category: 'leadership',
    locationType: 'office',
    location: 'Executive Boardroom A',
    meetingLink: 'https://meet.google.com/apex-executive-boardroom',
    reminderMinutes: 60,
    description: 'Executive leadership alignment on quarterly revenue, strategic goals, and risk management.',
    agenda: '1. Financial & revenue performance review (15 mins)\n2. Enterprise initiatives & roadmap updates (15 mins)\n3. Resource allocation & risk mitigation (15 mins)\n4. Executive decisions & action commitments (15 mins)',
    isDefault: true,
  },
  {
    id: 'tmpl-customer-kickoff',
    name: 'Customer Onboarding',
    title: 'Customer Implementation & Onboarding Kickoff',
    durationMinutes: 45,
    category: 'client',
    locationType: 'online',
    location: 'Customer Success Video Room',
    meetingLink: 'https://meet.google.com/apex-onboarding-kickoff',
    reminderMinutes: 30,
    description: 'Project kickoff to initiate onboarding schedule, integration points, and stakeholder roles.',
    agenda: '1. Stakeholder introductions & project governance (10 mins)\n2. Implementation scope & delivery schedule (20 mins)\n3. Security, single sign-on & account setup (10 mins)\n4. Q&A and next checkpoint scheduling (5 mins)',
    isDefault: true,
  },
];

export const initialImportHistory: import('./types').ImportHistoryRecord[] = [
  {
    id: 'imp-hist-1',
    filename: 'salesforce_enterprise_contacts_q3.csv',
    fileSize: 48920,
    sourceApp: 'salesforce_contacts',
    delimiter: ',',
    importedBy: 'user-1',
    importedByName: 'Sarah Jenkins (CEO)',
    timestamp: '2026-09-24T14:32:00Z',
    totalRecords: 45,
    successCount: 42,
    updatedCount: 3,
    duplicateCount: 3,
    failedCount: 0,
    status: 'Completed',
    duplicateHandlingMode: 'update',
  },
  {
    id: 'imp-hist-2',
    filename: 'outlook_executive_addressbook.csv',
    fileSize: 18450,
    sourceApp: 'outlook',
    delimiter: ',',
    importedBy: 'user-2',
    importedByName: 'David Ross (VP Sales)',
    timestamp: '2026-09-20T09:15:00Z',
    totalRecords: 18,
    successCount: 16,
    updatedCount: 0,
    duplicateCount: 1,
    failedCount: 1,
    status: 'Partially Completed',
    duplicateHandlingMode: 'skip',
    errorReport: [
      {
        rowNumber: 14,
        rawText: 'Dr. Gregory House,,greg@ppth.org,,Chief of Diagnostic',
        errors: ['Missing required last name field'],
      },
    ],
  },
  {
    id: 'imp-hist-3',
    filename: 'act_crm_client_migration_v2.txt',
    fileSize: 32110,
    sourceApp: 'act',
    delimiter: '\t',
    importedBy: 'user-1',
    importedByName: 'Sarah Jenkins (CEO)',
    timestamp: '2026-09-12T16:45:00Z',
    totalRecords: 28,
    successCount: 28,
    updatedCount: 0,
    duplicateCount: 0,
    failedCount: 0,
    status: 'Completed',
    duplicateHandlingMode: 'skip',
  },
];

export const initialExportHistory: import('./types').ExportHistoryRecord[] = [
  {
    id: 'exp-hist-1',
    entity: 'contacts',
    entityLabel: 'Contacts',
    filename: 'contacts_crm_export_2026-09-26.csv',
    format: 'csv',
    destination: 'download',
    delimiter: ',',
    encapsulation: 'double',
    rowSeparator: 'crlf',
    selectedFields: ['firstName', 'lastName', 'email', 'phone', 'jobTitle', 'companyId', 'type'],
    includeHeaders: true,
    recordsCount: 14,
    exportedBy: 'user-1',
    exportedByName: 'Sarah Jenkins (CEO)',
    timestamp: '2026-09-26T11:20:00Z',
    status: 'Completed',
    appliedFiltersSummary: 'Type: All, Owner: All',
    fileSize: 4210,
  },
  {
    id: 'exp-hist-2',
    entity: 'companies',
    entityLabel: 'Companies',
    filename: 'companies_directory_tab_delimited.txt',
    format: 'tab',
    destination: 'download',
    delimiter: '\t',
    encapsulation: 'double',
    rowSeparator: 'crlf',
    selectedFields: ['name', 'industry', 'annualRevenue', 'employeeCount', 'phone', 'website', 'priority'],
    includeHeaders: true,
    recordsCount: 7,
    exportedBy: 'user-2',
    exportedByName: 'David Ross (VP Sales)',
    timestamp: '2026-09-22T15:10:00Z',
    status: 'Completed',
    appliedFiltersSummary: 'Priority: All, Owner: David Ross',
    fileSize: 2890,
  },
  {
    id: 'exp-hist-3',
    entity: 'deals',
    entityLabel: 'Deals Pipeline',
    filename: 'active_deals_q3_excel.xls',
    format: 'excel',
    destination: 'excel',
    delimiter: ',',
    encapsulation: 'double',
    rowSeparator: 'crlf',
    selectedFields: ['title', 'company', 'contact', 'product', 'value', 'currency', 'stage', 'status'],
    includeHeaders: true,
    recordsCount: 12,
    exportedBy: 'user-1',
    exportedByName: 'Sarah Jenkins (CEO)',
    timestamp: '2026-09-20T14:40:00Z',
    status: 'Completed',
    appliedFiltersSummary: 'Status: Open, Date: This Quarter',
    fileSize: 8450,
  },
];

